import { Song } from "@/lib/types";

export const sampleSongs: Song[] = [
  {
    id: "sample-lagos-sunrise",
    title: "Lagos Sunrise",
    artist_name: "De Soundwave Studio",
    uploaded_by: "system",
    cover_url: "/covers/lagos-sunrise.jpg",
    audio_url: "/audio/lagos-sunrise.mp3",
    duration: 372,
    plays: 1240,
    genre: "afrobeats",
    lyrics: "Wake with the rhythm, move with the light, Lagos sunrise carries the night.",
    created_at: "2026-04-09T00:00:00.000Z",
  },
  {
    id: "sample-city-lights",
    title: "City Lights",
    artist_name: "De Soundwave Studio",
    uploaded_by: "system",
    cover_url: "/covers/city-lights.jpg",
    audio_url: "/audio/city-lights.mp3",
    duration: 348,
    plays: 980,
    genre: "pop",
    lyrics: "City lights and open roads, we move where the heartbeat glows.",
    created_at: "2026-04-08T00:00:00.000Z",
  },
  {
    id: "sample-midnight-drive",
    title: "Midnight Drive",
    artist_name: "De Soundwave Studio",
    uploaded_by: "system",
    cover_url: "/covers/midnight-drive.jpg",
    audio_url: "/audio/midnight-drive.mp3",
    duration: 335,
    plays: 2110,
    genre: "hip hop",
    lyrics: "Midnight drive, low lights, deep bass in the rearview.",
    created_at: "2026-04-07T00:00:00.000Z",
  },
  {
    id: "sample-gospel-glow",
    title: "Gospel Glow",
    artist_name: "De Soundwave Studio",
    uploaded_by: "system",
    cover_url: "/covers/gospel-glow.jpg",
    audio_url: "/audio/gospel-glow.mp3",
    duration: 310,
    plays: 860,
    genre: "gospel",
    lyrics: "Lift your voice, let hope arise, there is light in every sound.",
    created_at: "2026-04-06T00:00:00.000Z",
  },
  {
    id: "sample-ocean-breeze",
    title: "Ocean Breeze",
    artist_name: "De Soundwave Studio",
    uploaded_by: "system",
    cover_url: "/covers/ocean-breeze.jpg",
    audio_url: "/audio/ocean-breeze.mp3",
    duration: 355,
    plays: 670,
    genre: "r&b",
    lyrics: "Ocean breeze on a quiet tide, let the melody pull you wide.",
    created_at: "2026-04-05T00:00:00.000Z",
  },
];
