/**
 * Curated song titles from user library screenshots (metadata for search/discovery).
 * Playback still comes from a legal live provider when available — we do not host pirated MP3s.
 */
export interface CuratedSong {
  title: string;
  artist: string;
  featured?: string[];
  genre?: string;
}

export const curatedLibrarySongs: CuratedSong[] = [
  { title: "Anchovy", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Ada", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Apple Of My Eyes (Kuleko)", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Ijoya", artist: "Oritse Femi", featured: ["Remi Aluko"], genre: "Afrobeats" },
  { title: "Shaye Mi", artist: "Arbiz", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Pick Up", artist: "Adekunle Gold", genre: "Afrobeats" },
  { title: "5 Star (Remix)", artist: "Adekunle Gold", featured: ["Rick Ross"], genre: "Afrobeats" },
  { title: "Abule Sowo", artist: "Olamide", genre: "Afrobeats" },
  { title: "Abule", artist: "Patoranking", genre: "Dancehall" },
  { title: "Account Balance", artist: "Mohbad", featured: ["Zlatan"], genre: "Afrobeats" },
  { title: "Action Film", artist: "MI Abaga", featured: ["Brymo"], genre: "Hip Hop" },
  { title: "Ara", artist: "Brymo", genre: "Alternative" },
  { title: "2:30", artist: "Asake", genre: "Afrobeats" },
  { title: "Are You Sure", artist: "Lyta", featured: ["Naira Marley", "Zinoleesky", "EMO Grae"], genre: "Afrobeats" },
  { title: "Aquafina", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Anybody", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Sability", artist: "Ayra Starr", genre: "Afrobeats" },
  { title: "Rush", artist: "Ayra Starr", genre: "Afrobeats" },
  { title: "OLORUN BABALOLA", artist: "Elijah Akintunde", genre: "Gospel" },
  { title: "Ase Ti Jade", artist: "Toluwani Sings", genre: "Gospel" },
  { title: "B'ola (Honour)", artist: "Sunmisola Agbebi", genre: "Gospel" },
  { title: "Igbowo Eda", artist: "Tope Alabi", genre: "Gospel" },
  { title: "God Start With Me", artist: "Minister Oluwaferanmi", genre: "Gospel" },
  { title: "Live Ministration", artist: "Bidemi Olaoba", genre: "Gospel" },
  { title: "Best Of Davido Mix", artist: "DJ XOD", featured: ["Davido"], genre: "DJ Mix" },
  { title: "ASAP", artist: "Shallipopi", genre: "Afrobeats" },
  { title: "Aletile", artist: "Oritse Femi", featured: ["Small Doctor"], genre: "Afrobeats" },
  { title: "Akwa Ibom Ayaya", artist: "Mish", genre: "Afrobeats" },
  { title: "Aje", artist: "Diamond Jimma", featured: ["Stone D"], genre: "Afrobeats" },
  { title: "Aiye Ole", artist: "Barry Jhay", genre: "Afrobeats" },
  { title: "Ashe She", artist: "Barry Jhay", genre: "Afrobeats" },
  { title: "Afrohit Mix Vol 4", artist: "DJ Baddo", genre: "DJ Mix" },
  { title: "Amapiano Hype Cruise Mix Vol 2", artist: "DJ Baddo", featured: ["Hypeman Luckey"], genre: "DJ Mix" },
  { title: "Afro Jigga", artist: "Ladipoe", featured: ["Rema"], genre: "Hip Hop" },
  { title: "African Fever", artist: "Kaakie", featured: ["Sarkodie"], genre: "Afrobeats" },
  { title: "Adura Ololufe", artist: "Shola Allyson", genre: "Gospel" },
  { title: "Adura (Remix)", artist: "Oyinkanade", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Adua Ke O", artist: "Lawrence Oyor", genre: "Gospel" },
  { title: "Adua Ke O", artist: "Theophilus Sunday", genre: "Gospel" },
  { title: "Always", artist: "Darkoo", featured: ["Black Sherif"], genre: "Afrobeats" },
  { title: "Always", artist: "Skales", featured: ["Davido"], genre: "Afrobeats" },
  { title: "All The Way", artist: "Lil Kesh", genre: "Afrobeats" },
  { title: "All My Life", artist: "Adekunle Gold", genre: "Afrobeats" },
  { title: "All I Ever Need", artist: "Austin Mahone", genre: "Pop" },
  { title: "Alimi", artist: "Portable", genre: "Afrobeats" },
  { title: "Abuga", artist: "Alimi", featured: ["Portable"], genre: "Afrobeats" },
  { title: "Anabella", artist: "Khaid", genre: "Afrobeats" },
  { title: "American Faaji", artist: "Taye Currency", genre: "Fuji" },
  { title: "Amapiano", artist: "Asake", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Aye", artist: "Davido", genre: "Afrobeats" },
  { title: "Awww", artist: "Di'ja", genre: "Afrobeats" },
  { title: "Away", artist: "P-Square", genre: "Afrobeats" },
  { title: "Away", artist: "Davido", genre: "Afrobeats" },
  { title: "Ask About Me", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Asiwaju", artist: "Ruger", genre: "Afrobeats" },
  { title: "Bad Vibes", artist: "Ayra Starr", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Bad Girl Riri", artist: "Yonda", featured: ["Mayorkun"], genre: "Afrobeats" },
  { title: "Bad Boy", artist: "Oxlade", featured: ["Mayorkun"], genre: "Afrobeats" },
  { title: "Bad", artist: "Tiwa Savage", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Baba Eh", artist: "Esther Oji", genre: "Gospel" },
  { title: "BIG WIZZY (Italawa)", artist: "G.O.E", genre: "Afrobeats" },
  { title: "Banger", artist: "Rexxie", featured: ["Asake"], genre: "Afrobeats" },
  { title: "Bandana", artist: "Fireboy DML", featured: ["Asake"], genre: "Afrobeats" },
  { title: "Tshwala Bam", artist: "TitoM", featured: ["Yuppe", "S.N.E"], genre: "Amapiano" },
  { title: "Baddest Boy (Remix)", artist: "Skiibii", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Better", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Better Days", artist: "Sarkodie", featured: ["BNXN"], genre: "Afrobeats" },
  { title: "Best of Oritse Femi Mix Vol 1", artist: "DJ Doublesoud", featured: ["Oritse Femi"], genre: "DJ Mix" },
  { title: "Best Of Kizz Daniel Old vs New", artist: "DJ Tymix", featured: ["Kizz Daniel"], genre: "DJ Mix" },
  { title: "Best Of Davido Mixtape", artist: "DJ Selex", featured: ["Davido"], genre: "DJ Mix" },
  { title: "Benin Boys", artist: "Rema", featured: ["Shallipopi"], genre: "Afrobeats" },
  { title: "365 Days", artist: "Bella Shmurda", genre: "Afrobeats" },
  { title: "Beautiful Onyinye (Remix)", artist: "P-Square", featured: ["Rick Ross"], genre: "Afrobeats" },
  { title: "Beat To Beat Mix", artist: "DJ YK Mule", genre: "DJ Mix" },
  { title: "Basket Part 1", artist: "Taye Currency", genre: "Fuji" },
  { title: "Shako", artist: "Barry Jhay", genre: "Afrobeats" },
  { title: "Banging", artist: "Benzola", featured: ["Oritse Femi", "Figo M"], genre: "Afrobeats" },
  { title: "Bottom Belle", artist: "Omawumi", featured: ["Flavour"], genre: "Afrobeats" },
  { title: "Blessing (Remix)", artist: "Fridayy", featured: ["Asake"], genre: "Afrobeats" },
  { title: "Italy", artist: "Blaq Diamond", genre: "Amapiano" },
  { title: "Billion Dollar", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Big Energy", artist: "Ladipoe", genre: "Hip Hop" },
  { title: "Big Big Things", artist: "Young Jonn", featured: ["Kizz Daniel", "Seyi Vibez"], genre: "Afrobeats" },
  { title: "Calm Down", artist: "Rema", genre: "Afrobeats" },
  { title: "Call Of Duty", artist: "Zinoleesky", genre: "Afrobeats" },
  { title: "Call Me Every Day", artist: "Chris Brown", featured: ["Wizkid"], genre: "R&B" },
  { title: "Cocaina", artist: "Ayox", genre: "Afrobeats" },
  { title: "Chocolate", artist: "Slim Joe", genre: "Afrobeats" },
  { title: "Bursting My Brain", artist: "Innoweeny", featured: ["Oritse Femi", "Solid Star"], genre: "Afrobeats" },
  { title: "Bunieya Enu", artist: "P-Square", genre: "Afrobeats" },
  { title: "Kilometer", artist: "BNXN", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Buga", artist: "Kizz Daniel", featured: ["Tekno"], genre: "Afrobeats" },
  { title: "Bring It On", artist: "P-Square", featured: ["Dave Scott"], genre: "Afrobeats" },
  { title: "Breakfast", artist: "Iyanya", genre: "Afrobeats" },
  { title: "Boys With Love Mix", artist: "DJ Mix", featured: ["Rema", "Joeboy", "Fireboy DML"], genre: "DJ Mix" },
  { title: "Catalyst", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "MACHALA", artist: "Carterefe", featured: ["Berri-Tiga"], genre: "Afrobeats" },
  { title: "Carry Me Go", artist: "Khaid", featured: ["Boy Spyce"], genre: "Afrobeats" },
  { title: "Caro", artist: "Zinoleesky", featured: ["Naira Marley"], genre: "Afrobeats" },
  { title: "Caro", artist: "Tml Vibez", featured: ["Bella Shmurda"], genre: "Afrobeats" },
  { title: "Capable God", artist: "Judikay", genre: "Gospel" },
  { title: "Tikuku", artist: "Candy Bleakz", genre: "Afrobeats" },
  { title: "Come Back To Me", artist: "Adekunle Gold", featured: ["Khalid"], genre: "Afrobeats" },
  { title: "Collabo", artist: "DeeBee", genre: "Afrobeats" },
  { title: "Clear", artist: "Portable", genre: "Afrobeats" },
  { title: "Church", artist: "Olamide", featured: ["Viktoh"], genre: "Afrobeats" },
  { title: "Chop My Money", artist: "P-Square", featured: ["May D"], genre: "Afrobeats" },
  { title: "Chinedum", artist: "Mercy Chinwo", genre: "Gospel" },
  { title: "Chi Chi", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Chante Hallelujah", artist: "Ajuju", genre: "Gospel" },
  { title: "Chance (Na Ham)", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Champagne", artist: "KiDi", genre: "Afrobeats" },
  { title: "Chaduwa Ke O", artist: "Theophilus Sunday", genre: "Gospel" },
  { title: "Cough (Odo)", artist: "Kizz Daniel", featured: ["Empire"], genre: "Afrobeats" },
  { title: "Corny", artist: "Rema", genre: "Afrobeats" },
  { title: "Confam", artist: "Sarkodie", genre: "Hip Hop" },
  { title: "Love, Damini", artist: "Burna Boy", genre: "Afrobeats" },
  { title: "Commas", artist: "Ayra Starr", genre: "Afrobeats" },
  { title: "Coming", artist: "Naira Marley", featured: ["Busiswa"], genre: "Afrobeats" },
  { title: "Come Closer", artist: "Wizkid", featured: ["Drake"], genre: "Afrobeats" },
  { title: "Damn, Delilah", artist: "Adekunle Gold", genre: "Afrobeats" },
  { title: "Dadubule", artist: "Skaliey", genre: "Afrobeats" },
  { title: "DVer", artist: "Obong Etighi", genre: "Afrobeats" },
  { title: "Fokasibe", artist: "DJ Zeez", genre: "Afrobeats" },
  { title: "Savage Vibes", artist: "DJ Worldwide", featured: ["Lil Kesh", "Young Jonn"], genre: "DJ Mix" },
  { title: "Vibez On Vibez", artist: "DJ Speeddo", featured: ["Hype King Happy"], genre: "DJ Mix" },
  { title: "Best Of Lil Kesh 2017", artist: "DJ Baddo", featured: ["Lil Kesh"], genre: "DJ Mix" },
  { title: "Season Of Love Vol 2", artist: "DJ Baddo", genre: "DJ Mix" },
  { title: "DIA", artist: "Diamond Jimma", featured: ["Mohbad"], genre: "Afrobeats" },
  { title: "Country Side", artist: "Sarkodie", featured: ["Black Sherif"], genre: "Hip Hop" },
  { title: "Destiny", artist: "Boy Spyce", genre: "Afrobeats" },
  { title: "Tiff (Remix)", artist: "Demmie Vee", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Deja Vu", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Dealer", artist: "Ayo Maff", featured: ["Fireboy DML"], genre: "Afrobeats" },
  { title: "Darling", artist: "Seyi Vibez", featured: ["Simi"], genre: "Afrobeats" },
  { title: "Duffel Bag", artist: "Joeboy", genre: "Afrobeats" },
  { title: "Don't Matter", artist: "Akon", genre: "R&B" },
  { title: "Best of Dagrin Vs Olamide Mix", artist: "DJ S Boy", featured: ["Dagrin", "Olamide"], genre: "DJ Mix" },
  { title: "Dipatje", artist: "Felo Le Tee", featured: ["Myztro", "Daliwonga"], genre: "Amapiano" },
  { title: "Different Size", artist: "Burna Boy", featured: ["Victony"], genre: "Afrobeats" },
  { title: "Egwu", artist: "Chike", featured: ["Mohbad"], genre: "Afrobeats" },
  { title: "Ejika", artist: "Denike", genre: "Afrobeats" },
  { title: "Ebenezer", artist: "Nathaniel Bassey", featured: ["Victoria Orenze"], genre: "Gospel" },
  { title: "EWA", artist: "Seyi Vibez", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Dupe", artist: "Asake", genre: "Afrobeats" },
  { title: "Ere Gele", artist: "Lummyvibes", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Enu Gbe", artist: "Dotman", genre: "Afrobeats" },
  { title: "Enjoy Life", artist: "Xavior", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Emotional Blackmail", artist: "Olamide", featured: ["Kida Kudz"], genre: "Afrobeats" },
  { title: "Aye Si Mbe", artist: "EmmaOMG", genre: "Gospel" },
  { title: "Emi Mimo Ese", artist: "Toluwani Sings", genre: "Gospel" },
  { title: "Emi Lo Kan", artist: "Qdot", genre: "Afrobeats" },
  { title: "Ello Baby", artist: "Young Jonn", featured: ["Kizz Daniel", "Tiwa Savage"], genre: "Afrobeats" },
  { title: "Elele", artist: "Oritse Femi", featured: ["Qdot"], genre: "Afrobeats" },
  { title: "Elele", artist: "Emma Nyra", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Eleko", artist: "Mayorkun", genre: "Afrobeats" },
  { title: "Ele", artist: "Harrysong", genre: "Afrobeats" },
  { title: "Ekuro", artist: "Davido", genre: "Afrobeats" },
  { title: "For My Arena (Remix)", artist: "Small Baddo", featured: ["Idowest"], genre: "Afrobeats" },
  { title: "Flex", artist: "BNXN", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "First Time In America", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Ajoke", artist: "Fireboy DML", genre: "Afrobeats" },
  { title: "Peru", artist: "Fireboy DML", featured: ["Ed Sheeran"], genre: "Afrobeats" },
  { title: "Finesse", artist: "Pheelz", featured: ["BNXN"], genre: "Afrobeats" },
  { title: "Eze", artist: "Dare David", featured: ["Osby Berry"], genre: "Gospel" },
  { title: "Eyo", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Ewo Idi", artist: "Olamide", genre: "Afrobeats" },
  { title: "Feran Mi", artist: "Kizz Daniel", featured: ["Johnny Drille"], genre: "Afrobeats" },
  { title: "Feeling", artist: "Ladipoe", featured: ["BNXN"], genre: "Hip Hop" },
  { title: "Feel Good", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Falling Up", artist: "Adekunle Gold", featured: ["Pharrell Williams", "Nile Rodgers"], genre: "Afrobeats" },
  { title: "Fall In Love", artist: "D'banj", genre: "Afrobeats" },
  { title: "I Want It To Be You", artist: "Tatiana Manaois", featured: ["Mac Mase"], genre: "Pop" },
  { title: "Forever", artist: "P-Square", genre: "Afrobeats" },
  { title: "Forever Sweet", artist: "DOTTi The Deity", genre: "Afrobeats" },
  { title: "Forever (Remix)", artist: "Gyakie", featured: ["Omah Lay"], genre: "Afrobeats" },
  { title: "Forever", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "For My Hand", artist: "Burna Boy", featured: ["Ed Sheeran"], genre: "Afrobeats" },
  { title: "Gwagwalada", artist: "BNXN", featured: ["Kizz Daniel", "Seyi Vibez"], genre: "Afrobeats" },
  { title: "Goodbye (Warm Up)", artist: "Ayra Starr", featured: ["Asake"], genre: "Afrobeats" },
  { title: "Godly", artist: "Omah Lay", genre: "Afrobeats" },
  { title: "God Sent", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Gobe", artist: "Davido", genre: "Afrobeats" },
  { title: "Giza", artist: "Burna Boy", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Give It Up To Me", artist: "Sean Paul", genre: "Dancehall" },
  { title: "Girl", artist: "Bracket", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Ghost", artist: "Justin Bieber", genre: "Pop" },
  { title: "Gentility", artist: "Melvitto", featured: ["Wande Coal"], genre: "R&B" },
  { title: "Gbogbo Ogo", artist: "Ayo Ajewole", featured: ["Olaife Ayotunde"], genre: "Gospel" },
  { title: "Gbamu Gbamu", artist: "9ice", genre: "Afrobeats" },
  { title: "Gbabe", artist: "Lace", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Gangsta (Remix)", artist: "Seyi Vibez", featured: ["Russ", "Jibrille"], genre: "Afrobeats" },
  { title: "I Love Lagos", artist: "Olamide", genre: "Afrobeats" },
  { title: "I Like", artist: "J. Martins", genre: "Amapiano" },
  { title: "Hustler Anthem", artist: "King Falope", genre: "Afrobeats" },
  { title: "Hustle", artist: "Teni", genre: "Afrobeats" },
  { title: "Osekose", artist: "Hushpuppi", featured: ["Mohbad"], genre: "Afrobeats" },
  { title: "Hurry & Wait", artist: "Tiwa Savage", genre: "Afrobeats" },
  { title: "How Many Times", artist: "Timaya", featured: ["Iyaz"], genre: "Dancehall" },
  { title: "Highlife Interlude", artist: "Seyi Vibez", featured: ["Phyno"], genre: "Afrobeats" },
  { title: "Hello", artist: "T Dollar", genre: "Afrobeats" },
  { title: "Heaven", artist: "Davido", genre: "Afrobeats" },
  { title: "He Did It Again", artist: "Sinach", genre: "Gospel" },
  { title: "Happy Yourself", artist: "Reekado Banks", genre: "Afrobeats" },
  { title: "Happy 2024 Mix", artist: "Pella Iyke", featured: ["DJ Maximum"], genre: "DJ Mix" },
  { title: "Hallelujah", artist: "Johnny Drille", featured: ["Simi"], genre: "Afrobeats" },
  { title: "How Are You My Friend", artist: "Johnny Drille", genre: "Afrobeats" },
  { title: "Home Alone (Remix)", artist: "EddinzBani", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Holy One", artist: "Otega", genre: "Afrobeats" },
  { title: "Holy Holy", artist: "King Wadada", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Holla Holla", artist: "Akon", genre: "R&B" },
  { title: "History", artist: "Cheque", featured: ["Fireboy DML"], genre: "Afrobeats" },
  { title: "Highs & Lows", artist: "Prinz", genre: "Gospel" },
  { title: "Ibebe", artist: "DJ Xclusive", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Iya Gbogbo Yin", artist: "O Black", genre: "Afrobeats" },
  { title: "I'm the One", artist: "DJ Khaled", featured: ["Justin Bieber", "Quavo", "Chance the Rapper"], genre: "Hip Hop" },
  { title: "I Tried", artist: "Camylio", genre: "Pop" },
  { title: "I See Revival", artist: "Sweetleke", genre: "Gospel" },
  { title: "In My Maserati", artist: "Olakira", genre: "Afrobeats" },
  { title: "I'm a Mess", artist: "Omah Lay", genre: "Afrobeats" },
  { title: "Illegal", artist: "Pepenazi", featured: ["Olamide"], genre: "Hip Hop" },
  { title: "Ikwusigo (Remix)", artist: "J. Martins", featured: ["Innoss'B"], genre: "Afrobeats" },
  { title: "Ikwe", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Ijo Tiktok", artist: "Aloba Fresh", genre: "Afrobeats" },
  { title: "Igi Orombo", artist: "Sean Tizzle", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Igba Mi Tire Ni", artist: "Shola Allyson", genre: "Gospel" },
  { title: "Ifunanya", artist: "J. Martins", featured: ["DJ Arafat"], genre: "Afrobeats" },
  { title: "Ifa Wa Kayejo", artist: "Damidrizzy", genre: "Afrobeats" },
  { title: "If Love Is A Crime", artist: "2Baba", genre: "Afrobeats" },
  { title: "Ibile", artist: "Lil Kesh", genre: "Afrobeats" },
  { title: "Ibi Re", artist: "Qdot", featured: ["9ice", "Terry G"], genre: "Afrobeats" },
  { title: "Kelegbe", artist: "Olamide", featured: ["Lord Of Ajasa"], genre: "Afrobeats" },
  { title: "Katapot", artist: "Reekado Banks", genre: "Afrobeats" },
  { title: "Kalo Kalo", artist: "Davido", genre: "Afrobeats" },
  { title: "Just The Way", artist: "Aloma", featured: ["Mohbad", "Zinoleesky"], genre: "Afrobeats" },
  { title: "Jo", artist: "Teni", genre: "Afrobeats" },
  { title: "Jinja", artist: "Olamide", genre: "Afrobeats" },
  { title: "Jeje", artist: "DJ Xclusive", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Jehovah", artist: "Elevation Worship", genre: "Gospel" },
  { title: "Aje (Remix)", artist: "Jaywon", featured: ["Barry Jhay"], genre: "Afrobeats" },
  { title: "Jara", artist: "Khaid", genre: "Afrobeats" },
  { title: "Jaboti", artist: "Zlatan", genre: "Afrobeats" },
  { title: "Jesus", artist: "Esther Oji", genre: "Gospel" },
  { title: "Vibe Till Thy Kingdom Come", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Grinding", artist: "King Falope", featured: ["Alamin", "Dollarchase", "Pelly"], genre: "Afrobeats" },
  { title: "Jolie", artist: "Khaid", genre: "Afrobeats" },
  { title: "Kilometer (Remix)", artist: "BNXN", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Kelele", artist: "Oritse Femi", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Laye", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Lagos Boys", artist: "Laycon", genre: "Afrobeats" },
  { title: "Like You", artist: "Tatiana Manaois", genre: "Pop" },
  { title: "Like Ice Spice", artist: "Blaqbonez", genre: "Hip Hop" },
  { title: "Like", artist: "Reekado Banks", featured: ["Tiwa Savage", "Fiokee"], genre: "Afrobeats" },
  { title: "Lie", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Let Her Go", artist: "Passenger", genre: "Pop" },
  { title: "Le Kwa Ukwu", artist: "Iyanya", genre: "Afrobeats" },
  { title: "Love My Baby", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Loose It", artist: "Bella Shmurda", featured: ["Simi"], genre: "Afrobeats" },
  { title: "Loading", artist: "Olamide", featured: ["Bad Boy Timz"], genre: "Afrobeats" },
  { title: "Limpopo", artist: "Kcee", genre: "Afrobeats" },
  { title: "Don't Call Me", artist: "Lil Kesh", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Like", artist: "Iyanya", featured: ["Davido", "Kizz Daniel"], genre: "Afrobeats" },
  { title: "Ma Pariwo", artist: "Zinoleesky", genre: "Afrobeats" },
  { title: "MJ (Remix)", artist: "Bad Boy Timz", featured: ["Mayorkun"], genre: "Afrobeats" },
  { title: "Loyalist", artist: "DJ Kaywise", featured: ["Iyanya"], genre: "Afrobeats" },
  { title: "Loving You", artist: "Zinoleesky", genre: "Afrobeats" },
  { title: "Money (Remix)", artist: "MelodyVibes", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "NO", artist: "Meghan Trainor", genre: "Pop" },
  { title: "Chipi Ke Chipi", artist: "Mellow & Sleazy", featured: ["Justin99"], genre: "Amapiano" },
  { title: "Medicine", artist: "Jaywillz", genre: "Afrobeats" },
  { title: "Mayilo Mayibo", artist: "DJ YK Mule", genre: "DJ Mix" },
  { title: "Overloading (OVERDOSE)", artist: "Mavins", featured: ["Crayon", "Ayra Starr", "Ladipoe", "Magixx", "Boy Spyce"], genre: "Afrobeats" },
  { title: "Marlian Anthem", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Mama Yo", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Maga To Mugu", artist: "Davido", featured: ["Simi"], genre: "Afrobeats" },
  { title: "Sope", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Imole The Light Mix", artist: "DJ Lawy", featured: ["Mohbad"], genre: "DJ Mix" },
  { title: "Peace", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Mine", artist: "Teni", featured: ["DJ Neptune"], genre: "Afrobeats" },
  { title: "Mindset", artist: "Don Jay", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Metaverse", artist: "Olamide", genre: "Afrobeats" },
  { title: "Mercy", artist: "9ice", genre: "Afrobeats" },
  { title: "Mercy Received", artist: "TOLUccl", genre: "Gospel" },
  { title: "Nwa Baby (Ashawo)", artist: "Flavour", genre: "Afrobeats" },
  { title: "No Power Of Hell", artist: "Victor Thompson", genre: "Gospel" },
  { title: "No More Tuale", artist: "2Kriss", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "New Religion", artist: "Olamide", featured: ["Asake"], genre: "Afrobeats" },
  { title: "New Boy In Town", artist: "Elmah", genre: "Afrobeats" },
  { title: "Never Took the Time", artist: "Akon", genre: "R&B" },
  { title: "Normally", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Ole (Lazy)", artist: "Muraino", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Mungo Park", artist: "Korede Bello", genre: "Afrobeats" },
  { title: "Mu Emu", artist: "Olamide", featured: ["B Banks"], genre: "Afrobeats" },
  { title: "Mr Money", artist: "Asake", genre: "Afrobeats" },
  { title: "Move", artist: "Bad Boy Timz", genre: "Afrobeats" },
  { title: "Omo To Shan", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Oluwa Ni", artist: "Reekado Banks", genre: "Afrobeats" },
  { title: "Olowo Nla", artist: "Odunayo Akintomide", genre: "Gospel" },
  { title: "Olorun Agbaye (You Are Mighty)", artist: "Nathaniel Bassey", featured: ["Chandler Moore", "Oba"], genre: "Gospel" },
  { title: "Olorun", artist: "Asake", genre: "Afrobeats" },
  { title: "Ogwu Azu", artist: "JT Boyz", genre: "Afrobeats" },
  { title: "One Question", artist: "Wizkid", featured: ["Yemi Sax"], genre: "Afrobeats" },
  { title: "One Side", artist: "Iyanya", genre: "Afrobeats" },
  { title: "On Top Your Matter", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Omolope", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Omo To Shan", artist: "Olamide", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Orin Emi (Alomo Meta)", artist: "Qdot", genre: "Afrobeats" },
  { title: "Orimi", artist: "Remy T", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Ori Owo", artist: "Tillaman", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Ori Mi", artist: "CD Wonder", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Organise (Amapiano Dance Version)", artist: "DJ Skipo", featured: ["Asake"], genre: "Amapiano" },
  { title: "Opo", artist: "2Baba", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Over The Moon", artist: "Dr Sid", featured: ["K-Switch"], genre: "Afrobeats" },
  { title: "Oro Aje", artist: "Oritse Femi", featured: ["Portable"], genre: "Afrobeats" },
  { title: "Oro Aje 2", artist: "Oritse Femi", featured: ["Skales"], genre: "Afrobeats" },
  { title: "IRE", artist: "Oritse Femi", featured: ["Elizy"], genre: "Afrobeats" },
  { title: "Pray", artist: "Teni", featured: ["Phyno"], genre: "Afrobeats" },
  { title: "Am Not a Prisoner", artist: "Portable", genre: "Afrobeats" },
  { title: "Possible", artist: "9ice", genre: "Afrobeats" },
  { title: "Poko", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Poco Dance", artist: "Poco Lee", featured: ["Papayan"], genre: "Afrobeats" },
  { title: "YBNL", artist: "Olamide", genre: "Afrobeats" },
  { title: "Permit Me", artist: "Young Al", genre: "Afrobeats" },
  { title: "No More Condition", artist: "Rexxie", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Bounce", artist: "Rema", genre: "Afrobeats" },
  { title: "Realize", artist: "Balloranking", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Reason", artist: "Omah Lay", genre: "Afrobeats" },
  { title: "Raatan Lambiyan", artist: "Jubin Nautiyal", featured: ["Asees Kaur"], genre: "Bollywood" },
  { title: "RTID (Rich Till I Die)", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Gbeja", artist: "Qdot", featured: ["Pasuma"], genre: "Afrobeats" },
  { title: "Psalm 23", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Thy Kingdom Come", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Problem", artist: "Olamide", genre: "Afrobeats" },
  { title: "Preke Na Preke (Remix)", artist: "Super D", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Girlfriend", artist: "Ruger", genre: "Afrobeats" },
  { title: "Running", artist: "Ladipoe", featured: ["Fireboy DML"], genre: "Afrobeats" },
  { title: "Running (To You)", artist: "Chike", featured: ["Simi"], genre: "Afrobeats" },
  { title: "Rora", artist: "Lil Kesh", genre: "Afrobeats" },
  { title: "Ronaldo", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Romantic", artist: "Korede Bello", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Second Sermon", artist: "Black Sherif", genre: "Drill" },
  { title: "Scape Goat", artist: "D'banj", genre: "Afrobeats" },
  { title: "Sapa No Fit Catch Me", artist: "Nimix", genre: "Afrobeats" },
  { title: "Sabi", artist: "Mohbad", genre: "Afrobeats" },
  { title: "S.O.L.O", artist: "R2Bees", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Over Sabi", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Hat-trick", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Sexy Lady", artist: "Oritse Femi", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Selfmade", artist: "Lyta", genre: "Afrobeats" },
  { title: "See You Again", artist: "Wiz Khalifa", featured: ["Charlie Puth"], genre: "Hip Hop" },
  { title: "Aanu Ni", artist: "Bisimanuel", genre: "Gospel" },
  { title: "Chairman", artist: "Premium Emf", featured: ["Young Love"], genre: "Afrobeats" },
  { title: "Happy Day", artist: "Nexarito", genre: "Gospel" },
  { title: "New World Praise", artist: "Agatha Moses", genre: "Gospel" },
  { title: "Come and Praise God, Pt. 1", artist: "Agatha Moses", genre: "Gospel" },
  { title: "Oh Lord", artist: "Agatha Moses", genre: "Gospel" },
  { title: "Thank You", artist: "Agatha Moses", genre: "Gospel" },
  { title: "Sanumi", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Lost", artist: "Fola", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "OPRA MINI", artist: "Poco Lee", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Best of Kizz Daniel 2025 Mix", artist: "DJ Amacoz", featured: ["Kizz Daniel"], genre: "DJ Mix" },
  { title: "Fuji Garbage", artist: "Olamide", genre: "Afrobeats" },
  { title: "Nack Am", artist: "Candy Bleakz", featured: ["Portable"], genre: "Afrobeats" },
  { title: "Kukere (Remix)", artist: "Iyanya", featured: ["D'banj"], genre: "Afrobeats" },
  { title: "Naija Throwback Hit Mix", artist: "DJ Amacoz", genre: "DJ Mix" },
  { title: "Throwback 2015-2016 Mixtape", artist: "DJ Amacoz", genre: "DJ Mix" },
  { title: "Ara (600M)", artist: "Bella Shmurda", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "One Life", artist: "Skelvin", genre: "Afrobeats" },
  { title: "Fake Fam", artist: "Oritse Femi", featured: ["Sellah Malaika"], genre: "Afrobeats" },
  { title: "Uju", artist: "B Red", genre: "Afrobeats" },
  { title: "Uju (Remix)", artist: "B Red", featured: ["Duncan Mighty"], genre: "Afrobeats" },
  { title: "Alujo Yapa", artist: "DJ YK Mule", featured: ["Slattt"], genre: "DJ Mix" },
  { title: "Ojasope", artist: "Elijah Akintunde", genre: "Gospel" },
  { title: "EMI NI", artist: "Elijah Akintunde", genre: "Gospel" },
  { title: "Bi Moba Ranti", artist: "Elijah Akintunde", genre: "Gospel" },
  { title: "Ijo Odi", artist: "Elijah Akintunde", genre: "Gospel" },
  { title: "Kwantle Kwaa", artist: "Skavenja", featured: ["Sfear Nofokol"], genre: "Amapiano" },
  { title: "Toyin Tomato", artist: "Strei", genre: "Afrobeats" },
  { title: "Fine Lek", artist: "ApreeL", featured: ["Isat"], genre: "Afrobeats" },
  { title: "You Fine", artist: "Monalisa Stephen", featured: ["Oritse Femi", "Jaycode"], genre: "Afrobeats" },
  { title: "Olo Noni", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Style", artist: "Sabi", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Rila", artist: "South Plxya", featured: ["NerdFnd"], genre: "Afrobeats" },
  { title: "Oloruko Aperire", artist: "Jesukayode", genre: "Gospel" },
  { title: "Sha Guide", artist: "Portable", genre: "Afrobeats" },
  { title: "Symbol of Hope Mix", artist: "DJ Amacoz", featured: ["Tml Vibez", "Seyi Vibez", "T.I BLAZE"], genre: "DJ Mix" },
  { title: "Walking Dead", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Okay", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Ife", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Da Yan Mo", artist: "DJ Jimmy Jatt", featured: ["Lil Kesh", "Viktoh", "Olamide"], genre: "Afrobeats" },
  { title: "Omo Logo", artist: "Hysaint", featured: ["Qdot", "Oritse Femi"], genre: "Afrobeats" },
  { title: "Can't Change", artist: "Blo", genre: "Afrobeats" },
  { title: "Jogodo", artist: "Wizkid", featured: ["Asake"], genre: "Afrobeats" },
  { title: "Goated", artist: "Tml Vibez", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Body Tuff", artist: "Tml Vibez", featured: ["Ruger"], genre: "Afrobeats" },
  { title: "Hey Stranger", artist: "Reekado Banks", genre: "Afrobeats" },
  { title: "Birthday Praise", artist: "EmmaOMG", genre: "Gospel" },
  { title: "Ade Ori Okin", artist: "K1 De Ultimate", genre: "Fuji" },
  { title: "Onise Iyanu", artist: "Rotimikeys", featured: ["Gbenga Akinfenwa"], genre: "Gospel" },
  { title: "I'm Okay But I'm Not", artist: "Rhy Elliot", genre: "Pop" },
  { title: "Best of Olamide (The Return) Mix", artist: "DJ Baddo", featured: ["Olamide"], genre: "DJ Mix" },
  { title: "Eko Miami", artist: "Maleek Berry", genre: "Afrobeats" },
  { title: "Only Way (Remix)", artist: "Cazulee", featured: ["Bhadboi OML"], genre: "Afrobeats" },
  { title: "Shkran Lak", artist: "Bhadboi OML", genre: "Afrobeats" },
  { title: "7AM in Lekki", artist: "Bhadboi OML", genre: "Afrobeats" },
  { title: "Goodness", artist: "Bhadboi OML", genre: "Afrobeats" },
  { title: "Ogo", artist: "Danny S", genre: "Gospel" },
  { title: "Truth in the World", artist: "Lucky Dube", genre: "Reggae" },
  { title: "Easy (Jeje)", artist: "Reekado Banks", genre: "Afrobeats" },
  { title: "Best of Reekado Banks Mixtape", artist: "DJ Nasty", featured: ["Reekado Banks"], genre: "DJ Mix" },
  { title: "Hype Voltage 2025 Mixtape", artist: "DJ Amacoz", featured: ["Fola", "Shoday", "Seyi Vibez", "Asake"], genre: "DJ Mix" },
  { title: "Amapiano Road to 2026 Party Mixtape", artist: "DJ Fizzy", featured: ["DJ Spark", "Wizkid", "Burna Boy", "Davido"], genre: "DJ Mix" },
  { title: "Old School Naija Afrobeats Throwback", artist: "DJ Spark", featured: ["Iyanya", "Wizkid", "P-Square", "Olamide"], genre: "DJ Mix" },
  { title: "Kude", artist: "Harry Cane", featured: ["Master KG", "Teejay", "Ntando Yamahlubi"], genre: "Amapiano" },
  { title: "Meow", artist: "Scope", featured: ["Qdot"], genre: "Afrobeats" },
  { title: "Confession", artist: "Babyboy AV", genre: "Afrobeats" },
  { title: "Praiservation Gospel Mix", artist: "DJ Alinco", genre: "DJ Mix" },
  { title: "Wonderful", artist: "Tmizzy Mrhorrizen", genre: "Gospel" },
  { title: "Sooner", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Go Hard", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Sharpally", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Full My Tank", artist: "Young Jonn", featured: ["Don Jazzy"], genre: "Afrobeats" },
  { title: "50 Billion", artist: "Young Jonn", featured: ["Zlatan"], genre: "Afrobeats" },
  { title: "Maya Maya", artist: "Young Jonn", featured: ["Ya Levis"], genre: "Afrobeats" },
  { title: "Something Big", artist: "Delana Hope", featured: ["Dickson Mwita"], genre: "Gospel" },
  { title: "Where You Are", artist: "Keenan Te", genre: "Gospel" },
  { title: "Memories", artist: "Keenan Te", genre: "Gospel" },
  { title: "To Understand", artist: "The Blue Collar Believer", genre: "Gospel" },
  { title: "Sacred Battles", artist: "The Blue Collar Believer", genre: "Gospel" },
  { title: "Gone But Not Forgotten", artist: "The Blue Collar Believer", genre: "Gospel" },
  { title: "Only Heaven Knows", artist: "The Blue Collar Believer", genre: "Gospel" },
  { title: "Self Made in America", artist: "Overtime", genre: "Hip Hop" },
  { title: "Stronger", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Jeje", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Bahamas", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Pot of Gold", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "Tony Montana", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "2Factor", artist: "Young Jonn", featured: ["Asake", "Focalistic"], genre: "Afrobeats" },
  { title: "My Way", artist: "Hotkid", genre: "Afrobeats" },
  { title: "Many People", artist: "Adekunle Gold", genre: "Afrobeats" },
  { title: "Water Water Yansh", artist: "DJ OBA45", featured: ["Muripounds", "Emmyblaqcfr"], genre: "Afrobeats" },
  { title: "Snokonoko", artist: "Al Xapo", featured: ["Benzoo", "EeQue"], genre: "Amapiano" },
  { title: "Fuji Fusion", artist: "Bella Shmurda", featured: ["K1 De Ultimate"], genre: "Afrobeats" },
  { title: "Fuji Moto", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Blue Collar", artist: "Jonathan Hutcherson", genre: "Gospel" },
  { title: "Murder", artist: "King Perryy", featured: ["Teni"], genre: "Afrobeats" },
  { title: "Gbese", artist: "Majeeed", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Reggae Mashup Mix", artist: "DJ Symple", featured: ["Lucky Dube", "Bob Marley"], genre: "DJ Mix" },
  { title: "Best of Lucky Dube Mixtape", artist: "Deejay Biggy", featured: ["Lucky Dube"], genre: "DJ Mix" },
  { title: "Victims", artist: "Lucky Dube", genre: "Reggae" },
  { title: "Oleku", artist: "Ice Prince", featured: ["Brymo"], genre: "Hip Hop" },
  { title: "Kelegbe", artist: "Small Doctor", featured: ["DJ Baddo"], genre: "Afrobeats" },
  { title: "Aboki", artist: "Ice Prince", genre: "Hip Hop" },
  { title: "Kasongo", artist: "Harry Cane", featured: ["Dr Tawanda", "Nelcy B"], genre: "Amapiano" },
  { title: "Vuvuzela", artist: "Sando Cynthia", featured: ["Harry Cane", "DJ Anunnaki"], genre: "Amapiano" },
  { title: "Real Life", artist: "Jonah Lanez", genre: "Afrobeats" },
  { title: "Ka Ma Ma Ri", artist: "Tope Alabi", featured: ["BBO", "Eyitayo"], genre: "Gospel" },
  { title: "Miracle Worker", artist: "Uchenna Okereke", genre: "Gospel" },
  { title: "Hood Scars 2", artist: "J.I the Prince of N.Y", featured: ["Lil Tjay"], genre: "Hip Hop" },
  { title: "Tit for Tat", artist: "Tate McRae", genre: "Pop" },
  { title: "Dry Wave", artist: "JFS Music", featured: ["King Tone", "Soa Mattrix"], genre: "Amapiano" },
  { title: "Osunmo Grammy", artist: "Portable", genre: "Afrobeats" },
  { title: "Kamake", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Nana", artist: "Diamond Platnumz", featured: ["Flavour"], genre: "Bongo Flava" },
  { title: "Time To Party", artist: "Flavour", featured: ["Diamond Platnumz"], genre: "Afrobeats" },
  { title: "Copines", artist: "Aya Nakamura", genre: "Pop" },
  { title: "Gbogbonise", artist: "Pelumi Deborah", genre: "Gospel" },
  { title: "Throwback Hit Mix Vol 2", artist: "DJ Baddo", genre: "DJ Mix" },
  { title: "We Bow Down", artist: "Testimony Jaga", genre: "Gospel" },
  { title: "Who You Say I Am", artist: "Hillsong Worship", genre: "Gospel" },
  { title: "Arike", artist: "Kunmie", genre: "Afrobeats" },
  { title: "Arike (Remix)", artist: "Kunmie", featured: ["Mabel", "Simi"], genre: "Afrobeats" },
  { title: "Okpeke", artist: "Phyno", featured: ["Flavour", "2Baba"], genre: "Afrobeats" },
  { title: "Looking Nyash", artist: "Flavour", genre: "Afrobeats" },
  { title: "Me & You", artist: "Bracket", genre: "Afrobeats" },
  { title: "Number One (Remix)", artist: "Diamond Platnumz", featured: ["Davido"], genre: "Bongo Flava" },
  { title: "Duro", artist: "Tekno", genre: "Afrobeats" },
  { title: "To Be A Man", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Early 2K", artist: "Chris Brown", featured: ["Tank"], genre: "R&B" },
  { title: "Ara", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Work Around", artist: "Lanre Teriba", featured: ["Oritse Femi", "Iblaze"], genre: "Afrobeats" },
  { title: "Beautiful Day", artist: "Akon", genre: "R&B" },
  { title: "Your Love", artist: "Nicki Minaj", genre: "Hip Hop" },
  { title: "Adigun Ojuwonlo", artist: "9ice", genre: "Afrobeats" },
  { title: "What A Beautiful Name", artist: "Hillsong Worship", genre: "Gospel" },
  { title: "Up Tempo Mix", artist: "DJ Alinco", genre: "DJ Mix" },
  { title: "Kojosese", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Idi Oremi (Opotoyi 2)", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Tesumole", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Dakun", artist: "Olawale Imole", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Me And Love Don't Get Along", artist: "Tatiana Manaois", genre: "Pop" },
  { title: "Fun", artist: "Rema", featured: ["Paraziii"], genre: "Afrobeats" },
  { title: "Bom Bom", artist: "Mohbad", featured: ["Afrob"], genre: "Afrobeats" },
  { title: "Bum Bum", artist: "Timaya", genre: "Afrobeats" },
  { title: "Bubalu", artist: "Feid", featured: ["Rema"], genre: "Reggaeton" },
  { title: "Spirit", artist: "Vicoka", featured: ["Wizard Chan"], genre: "Afrobeats" },
  { title: "Too Faithful", artist: "Moses Bliss", genre: "Gospel" },
  { title: "Love in This Club", artist: "Usher", featured: ["Young Jeezy"], genre: "R&B" },
  { title: "Call Me", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Omoge", artist: "Slim Joe", featured: ["Iyanya"], genre: "Afrobeats" },
  { title: "Give It 2 Me", artist: "Kcee", featured: ["Flavour"], genre: "Afrobeats" },
  { title: "DJ Tolly P Mixtape", artist: "DJ Tolly P", genre: "DJ Mix" },
  { title: "Biko!", artist: "Lola Rae", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Porsche", artist: "T.I BLAZE", genre: "Afrobeats" },
  { title: "E No Go Finish", artist: "King Soundboi", featured: ["Portable"], genre: "Afrobeats" },
  { title: "Sandra Benede", artist: "Portable", featured: ["Terry Apala"], genre: "Afrobeats" },
  { title: "Jailer", artist: "Olamide", featured: ["Jaywillz"], genre: "Afrobeats" },
  { title: "Dodoyo Mentality", artist: "Portable", genre: "Afrobeats" },
  { title: "Folded", artist: "Kehlani", genre: "R&B" },
  { title: "Girls Like Us", artist: "Zoe Wees", genre: "Pop" },
  { title: "Daddy's Eyes", artist: "Zoe Wees", genre: "Pop" },
  { title: "Nothing But You", artist: "Zoe Wees", genre: "Pop" },
  { title: "Thing I Want", artist: "Mr Pee", genre: "Afrobeats" },
  { title: "Fragile Thing", artist: "Winona Oak", genre: "Pop" },
  { title: "You Are My Forever Love", artist: "Varisha Shakila", genre: "Gospel" },
  { title: "BBO", artist: "My God", genre: "Gospel" },
  { title: "I Alone", artist: "BNXN", genre: "Afrobeats" },
  { title: "Could This Be Love", artist: "Nasboi", featured: ["Chike"], genre: "Afrobeats" },
  { title: "Billionaires Club", artist: "Olamide", featured: ["Wizkid", "Darkoo"], genre: "Afrobeats" },
  { title: "Free", artist: "Olamide", featured: ["Seyi Vibez", "Muyeez"], genre: "Afrobeats" },
  { title: "Very Soon", artist: "BNXN", featured: ["Fola"], genre: "Afrobeats" },
  { title: "99", artist: "Olamide", featured: ["Seyi Vibez", "Asake", "Young Jonn", "Daecolm"], genre: "Afrobeats" },
  { title: "Ijebu", artist: "Modupe", featured: ["Qdot"], genre: "Afrobeats" },
  { title: "Orijin", artist: "Qdot", genre: "Afrobeats" },
  { title: "Ijo Gelede", artist: "Qdot", genre: "Afrobeats" },
  { title: "Maria", artist: "Qdot", featured: ["Xsmile"], genre: "Afrobeats" },
  { title: "Duro", artist: "Qdot", genre: "Afrobeats" },
  { title: "Group Chat", artist: "Portable", genre: "Afrobeats" },
  { title: "Okiemute (Remix)", artist: "Yungskid", featured: ["Mohbad"], genre: "Afrobeats" },
  { title: "Your Waist", artist: "Iyanya", genre: "Afrobeats" },
  { title: "Id.Me", artist: "Rybeena", genre: "Afrobeats" },
  { title: "Prodigal", artist: "Rybeena", genre: "Afrobeats" },
  { title: "Gaddem", artist: "Rybeena", featured: ["Shoday"], genre: "Afrobeats" },
  { title: "1999", artist: "Rybeena", genre: "Afrobeats" },
  { title: "Aje", artist: "DMW", featured: ["Davido", "Peruzzi", "Yonda", "Fresh VDM"], genre: "Afrobeats" },
  { title: "Bounce", artist: "Ruger", genre: "Afrobeats" },
  { title: "Far Away", artist: "Zyno Bwoy", genre: "Afrobeats" },
  { title: "My God", artist: "BBO", genre: "Gospel" },
  { title: "Al-Jannah", artist: "Kizz Daniel", featured: ["Odumodublvck", "Bella Shmurda"], genre: "Afrobeats" },
  { title: "Love", artist: "Burna Boy", genre: "Afrobeats" },
  { title: "Umbrella (Remix)", artist: "Nasboi", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Best of Kizz Daniel Mix", artist: "DJ Baddo", featured: ["Kizz Daniel"], genre: "DJ Mix" },
  { title: "For The Streets", artist: "Inayah", genre: "R&B" },
  { title: "Boys Are Bad", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Molue", artist: "Kizz Daniel", featured: ["Sugarboy"], genre: "Afrobeats" },
  { title: "Are You Alright", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Day By Day", artist: "Simi", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Emi Mimo", artist: "Eroomi", genre: "Gospel" },
  { title: "Banana", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Bumpa", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Rhude Gyal", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Lagos Party (Remix)", artist: "Banky W", genre: "Afrobeats" },
  { title: "With You", artist: "Davido", genre: "Afrobeats" },
  { title: "My Darling", artist: "Chella", genre: "Afrobeats" },
  { title: "Yahyuppiyah", artist: "Uncle Waffles", featured: ["Tony Duardo", "Justin99", "Pcee", "EeQue", "Chley"], genre: "Amapiano" },
  { title: "Skala V", artist: "Hotkeed", featured: ["T Dollar"], genre: "Afrobeats" },
  { title: "Snap", artist: "Rosa Linn", genre: "Pop" },
  { title: "A Very Big God", artist: "Toluwani Sings", genre: "Gospel" },
  { title: "Adimula", artist: "Portable", genre: "Afrobeats" },
  { title: "Titi", artist: "Kizz Daniel", featured: ["Fola"], genre: "Afrobeats" },
  { title: "Black Girl Magic", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Bebo", artist: "Burna Boy", genre: "Afrobeats" },
  { title: "Savage", artist: "DJ Worldwide", featured: ["Lil Kesh"], genre: "Afrobeats" },
  { title: "Play Am (Remix)", artist: "Young D", featured: ["Oritse Femi", "DJ Norie", "Burna Boy", "Konshens"], genre: "Afrobeats" },
  { title: "Ngishutheni", artist: "Goon Flavour", featured: ["Master KG", "Eemoh"], genre: "Amapiano" },
  { title: "TikTok Amapiano Sound Mixtape", artist: "DJ Danny Yung", genre: "DJ Mix" },
  { title: "44-4 Foti", artist: "Baddy Oosha", featured: ["Naira Marley"], genre: "Afrobeats" },
  { title: "Agbalumo", artist: "Seriki", genre: "Afrobeats" },
  { title: "Dollar For Love (Baby)", artist: "Thuto The Human", genre: "Amapiano" },
  { title: "Ka Valungu", artist: "Tebza De DJ", featured: ["DJ Nomza The King"], genre: "Amapiano" },
  { title: "Tjeya", artist: "The Lowkeys", featured: ["Sims Noreng"], genre: "Amapiano" },
  { title: "Forever Yena 2.0", artist: "Major Keys", genre: "Amapiano" },
  { title: "Mnike", artist: "Tyler ICU", genre: "Amapiano" },
  { title: "Miliki Rave Vol 1", artist: "Fujicologist", genre: "DJ Mix" },
  { title: "See Me See God (SMSG)", artist: "Barry Jhay", genre: "Afrobeats" },
  { title: "The Chairman", artist: "MI Abaga", featured: ["Oritse Femi", "Frank Edwards"], genre: "Hip Hop" },
  { title: "Duro", artist: "Kodee", genre: "Afrobeats" },
  { title: "Lorile", artist: "X Project", genre: "Afrobeats" },
  { title: "Foreign Old School Mix", artist: "DJ Amacoz", genre: "DJ Mix" },
  { title: "Trap Is Lit Vol 1", artist: "DJ Amacoz", genre: "DJ Mix" },
  { title: "Afro Fun Mix", artist: "DJ Amacoz", genre: "DJ Mix" },
  { title: "Best of Oritse Femi Mix", artist: "DJ Lovely", featured: ["Oritse Femi"], genre: "DJ Mix" },
  { title: "Street Runner", artist: "Rod Wave", genre: "Hip Hop" },
  { title: "Ire", artist: "Adekunle Gold", genre: "Afrobeats" },
  { title: "Loni Loma Deleyin", artist: "Rudy Omoibile", genre: "Afrobeats" },
  { title: "Fuji Garbage", artist: "Zinoleesky", genre: "Afrobeats" },
  { title: "New Taker", artist: "Rybeena", genre: "Afrobeats" },
  { title: "Cruise", artist: "Tml Vibez", featured: ["DJ 4kerty"], genre: "Afrobeats" },
  { title: "7.5G", artist: "Balloranking", genre: "Afrobeats" },
  { title: "Boss", artist: "Tml Vibez", featured: ["DJ 4kerty"], genre: "Afrobeats" },
  { title: "Find Money", artist: "Ayo Maff", featured: ["Zerrydl"], genre: "Afrobeats" },
  { title: "Without Me", artist: "Halsey", featured: ["Juice WRLD"], genre: "Pop" },
  { title: "Another Level", artist: "Patoranking", genre: "Dancehall" },
  { title: "Happy Song", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Beautiful Girls", artist: "Sean Kingston", genre: "Pop" },
  { title: "Loke Loke", artist: "Sean Tizzle", featured: ["9ice"], genre: "Afrobeats" },
  { title: "Diana", artist: "Tekno", genre: "Afrobeats" },
  { title: "I Don't Love You Like I Used To", artist: "Jojo Leo", featured: ["JayBenz"], genre: "Afrobeats" },
  { title: "Oriade", artist: "Portable", genre: "Afrobeats" },
  { title: "Police", artist: "Kizz Daniel", featured: ["Angelique Kidjo", "Johnny Drille"], genre: "Afrobeats" },
  { title: "Saka Nana", artist: "Uhuru", featured: ["DJ Tira", "TradeMark", "Mashabela"], genre: "Kwaito" },
  { title: "Best Throwback Uniform Blues Mixtape", artist: "DJ Rider", genre: "DJ Mix" },
  { title: "Children of Africa", artist: "Seyi Vibez", genre: "Afrobeats" },
  { title: "Kiss Me", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Duro", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "My People", artist: "Korede Bello", featured: ["Lil Kesh"], genre: "Afrobeats" },
  { title: "Surrender", artist: "Mr Eazi", featured: ["Simi"], genre: "Afrobeats" },
  { title: "Spirit", artist: "Olamide", genre: "Afrobeats" },
  { title: "Love No Go Die", artist: "Olamide", genre: "Afrobeats" },
  { title: "See Finish", artist: "Gingo", featured: ["Mayorkun"], genre: "Afrobeats" },
  { title: "Nothing Dey", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Give Into", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Napo", artist: "Kizz Daniel", featured: ["Sugarboy"], genre: "Afrobeats" },
  { title: "Jombo", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Reliable Pt. 5", artist: "Saheed Osupa", genre: "Fuji" },
  { title: "Mama", artist: "Mayorkun", genre: "Afrobeats" },
  { title: "Nuttin Nuh Go So", artist: "Notch", featured: ["Tony CD Kelly"], genre: "Dancehall" },
  { title: "Implication", artist: "2Baba", genre: "Afrobeats" },
  { title: "The Way It Is", artist: "Lucky Dube", genre: "Reggae" },
  { title: "Girlie O (Remix)", artist: "Patoranking", featured: ["Tiwa Savage"], genre: "Dancehall" },
  { title: "Yes Melo (Remix)", artist: "Dotman", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Melo Melo", artist: "Olamide", genre: "Afrobeats" },
  { title: "Chop My Money", artist: "P-Square", featured: ["Akon", "May D"], genre: "Afrobeats" },
  { title: "San Bori Bobo", artist: "Sauce Kid", featured: ["Ghetto P"], genre: "Hip Hop" },
  { title: "I Concur", artist: "Timaya", featured: ["Don Jazzy"], genre: "Afrobeats" },
  { title: "Nek-Unek", artist: "MC Galaxy", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Sekem", artist: "MC Galaxy", genre: "Afrobeats" },
  { title: "Moni Baba Kan", artist: "Lara George", genre: "Gospel" },
  { title: "Yes/No", artist: "Banky W", genre: "Afrobeats" },
  { title: "1999", artist: "Olamide", genre: "Afrobeats" },
  { title: "100 to Million", artist: "Olamide", featured: ["Viktoh", "Chinko Ekun"], genre: "Afrobeats" },
  { title: "Warn Dem", artist: "DJ Kaywise", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Black Is Beautiful", artist: "Flavour", genre: "Afrobeats" },
  { title: "Adun", artist: "Sunmisola Agbebi", featured: ["Yinka Okeleye"], genre: "Gospel" },
  { title: "Sorry", artist: "Justin Bieber", genre: "Pop" },
  { title: "Carry Go (Remix)", artist: "Pryme", featured: ["Chike"], genre: "Afrobeats" },
  { title: "Best of Small Doctor Mixtape", artist: "DJ Wizkel", featured: ["Small Doctor"], genre: "DJ Mix" },
  { title: "Peaches", artist: "Justin Bieber", genre: "Pop" },
  { title: "Omo Mumini", artist: "Ameenat Ajao", genre: "Gospel" },
  { title: "Hotter Than Fire", artist: "Dr Pat", featured: ["Sheyman"], genre: "Afrobeats" },
  { title: "Daddy Yo", artist: "Wizkid", featured: ["Efya"], genre: "Afrobeats" },
  { title: "Aiye Mi (Remix)", artist: "Dayo Amusa", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Imagine That", artist: "Styl-Plus", genre: "Afrobeats" },
  { title: "Oliver Twist", artist: "D'banj", genre: "Afrobeats" },
  { title: "Yori Yori", artist: "Bracket", genre: "Afrobeats" },
  { title: "Kerewa", artist: "Zule Zoo", genre: "Afrobeats" },
  { title: "Komolop", artist: "MC Galaxy", genre: "Afrobeats" },
  { title: "Best of Lil Kesh 2025 Mixtape", artist: "DJ Amacoz", featured: ["Lil Kesh"], genre: "DJ Mix" },
  { title: "Best of Davido Mix", artist: "DJ Baddo", featured: ["Davido"], genre: "DJ Mix" },
  { title: "Jaiye", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Want It", artist: "Oritse Femi", featured: ["Shatta Wale", "Cynthia Morgan"], genre: "Afrobeats" },
  { title: "Underrate", artist: "Zealot", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Ile Aiye", artist: "Oritse Femi", featured: ["H.H.S"], genre: "Afrobeats" },
  { title: "On Rewind", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Money", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Mosore Ekende Funmi", artist: "Ameenat Ajao", genre: "Gospel" },
  { title: "Mama Ni Mama Mi", artist: "Ameenat Ajao", genre: "Gospel" },
  { title: "Amin", artist: "Dammy Krane", genre: "Afrobeats" },
  { title: "Amin Ase", artist: "Dammy Krane", featured: ["K1 De Ultimate"], genre: "Afrobeats" },
  { title: "Kabiyesi", artist: "Dr SID", genre: "Afrobeats" },
  { title: "Peace I Chose", artist: "Kizz Daniel", featured: ["Runtown"], genre: "Afrobeats" },
  { title: "Love Me Like You Do", artist: "Ellie Goulding", genre: "Pop" },
  { title: "Iya Alariya", artist: "9ice", genre: "Afrobeats" },
  { title: "The Sound of Silence (CYRIL Remix)", artist: "Disturbed", featured: ["CYRIL"], genre: "Electronic" },
  { title: "U Ngandidii", artist: "Sfisoman", genre: "Amapiano" },
  { title: "Dali Wami", artist: "King Temoso", featured: ["Master KG", "Nkosazana Daughter", "Nobuhle"], genre: "Amapiano" },
  { title: "Amapiano Hits December Mix", artist: "Wanitwa Mos", featured: ["Harry Cane", "Master KG", "King Temoso"], genre: "DJ Mix" },
  { title: "Inhliziyo", artist: "HBK Live Act", featured: ["AmaSiblings", "Black Blondy"], genre: "Amapiano" },
  { title: "Jealousy", artist: "Khalil Harrison", featured: ["Tyler ICU"], genre: "Amapiano" },
  { title: "Ramadan", artist: "Tolibian", genre: "Gospel" },
  { title: "Dada Awuru Mongala", artist: "Ogoeri", genre: "Afrobeats" },
  { title: "Best of Seyi Vibez Mix", artist: "DJ Black", featured: ["Seyi Vibez"], genre: "DJ Mix" },
  { title: "Tshwala Bam (Remix)", artist: "TitoM", featured: ["Yuppe", "Burna Boy", "S.N.E"], genre: "Amapiano" },
  { title: "Upgrade", artist: "Bella Shmurda", genre: "Afrobeats" },
  { title: "Iwokolodami", artist: "Goke Bajowa", genre: "Gospel" },
  { title: "Loyal", artist: "Major Lazer", featured: ["Kizz Daniel", "Kranium"], genre: "Dancehall" },
  { title: "Pipa", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Somebody", artist: "Skiibii", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Oyibe", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Time No Dey", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Se Bi Wo", artist: "Lace", featured: ["Yemi Alade"], genre: "Afrobeats" },
  { title: "Danfo Driver (Remix)", artist: "Danfo Drivers", genre: "Afrobeats" },
  { title: "Ajegunle Mix Vol. 3", artist: "DJ Fletzy", genre: "DJ Mix" },
  { title: "Tie Me Up", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Eni Duro", artist: "Olamide", genre: "Afrobeats" },
  { title: "Flavor", artist: "Jeleel", genre: "Afrobeats" },
  { title: "Yankulu Ya (Dem Mama Remix)", artist: "Timaya", genre: "Afrobeats" },
  { title: "U Go Kill Me", artist: "Sarkodie", genre: "Hip Hop" },
  { title: "Jaho", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Happy", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Raba", artist: "DJ Shabsy", featured: ["Kizz Daniel", "Sugarboy"], genre: "Afrobeats" },
  { title: "E'better", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Chana", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "True", artist: "Mayorkun", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "No Do", artist: "Flyboy INC", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Throwback Olamide Mix", artist: "DJ Prince", featured: ["Olamide"], genre: "DJ Mix" },
  { title: "Only Me", artist: "Asake", genre: "Afrobeats" },
  { title: "Will You Be There", artist: "Michael Jackson", genre: "Pop" },
  { title: "Oju Tiwon", artist: "Danny Young", featured: ["Ojoro"], genre: "Afrobeats" },
  { title: "Kojo", artist: "Lil Kesh", genre: "Afrobeats" },
  { title: "Soweto Baby", artist: "DJ Maphorisa", featured: ["Wizkid", "DJ Buckz"], genre: "Afrobeats" },
  { title: "Gweta", artist: "Toofan", genre: "Afrobeats" },
  { title: "Nowo Soke", artist: "CDQ", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "This Kind Luv", artist: "Patoranking", featured: ["Wizkid"], genre: "Dancehall" },
  { title: "Yapa (Remix)", artist: "Masterkraft", featured: ["Wizkid", "Reekado Banks", "CDQ"], genre: "Afrobeats" },
  { title: "One and Only", artist: "Korede Bello", genre: "Afrobeats" },
  { title: "10 Over 10", artist: "Naeto C", genre: "Hip Hop" },
  { title: "Control", artist: "Zoe Wees", genre: "Pop" },
  { title: "Eru Jeje", artist: "Bola Are", genre: "Gospel" },
  { title: "Pxy Drip", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "My Woman, My Everything", artist: "Patoranking", featured: ["Wande Coal"], genre: "Dancehall" },
  { title: "Ireti", artist: "Oritse Femi", featured: ["Lil Kesh"], genre: "Afrobeats" },
  { title: "Best of Oritse Femi Mix Vol 2", artist: "DJ Doublesoud", featured: ["Oritse Femi"], genre: "DJ Mix" },
  { title: "Sugbon Aiye Mi", artist: "Emeka Indo", genre: "Gospel" },
  { title: "Arugbo Ojo", artist: "Emeka Indo", genre: "Gospel" },
  { title: "Agbara Olorun", artist: "Emeka Indo", genre: "Gospel" },
  { title: "Kolo 1", artist: "Emeka Indo", genre: "Gospel" },
  { title: "Kolo 2", artist: "Emeka Indo", genre: "Gospel" },
  { title: "Joy Is Coming", artist: "Fido", genre: "Afrobeats" },
  { title: "Jerimoyah", artist: "Wizka", genre: "Afrobeats" },
  { title: "Trust", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Aya Oba (Queen)", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "Best of Shadykarz Mix", artist: "DJ Pelzy", featured: ["Shadykarz"], genre: "DJ Mix" },
  { title: "Calvary 2.0", artist: "Shadykarz", featured: ["Idowest"], genre: "Afrobeats" },
  { title: "Do", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "Omodele", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "Perfect", artist: "Ed Sheeran", genre: "Pop" },
  { title: "Mercies of the Lord", artist: "Oritse Femi", featured: ["Dagrin", "Rymzo", "Shinny"], genre: "Afrobeats" },
  { title: "Unity", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Life", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Laye", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Cardiac", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Double Wahala", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Testimony", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Give Thanks", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "God Pikin", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Ara N Bada", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Mr Gomina", artist: "Shadykarz", featured: ["Flekta Man"], genre: "Afrobeats" },
  { title: "Relationship", artist: "Berri-Tiga", featured: ["Peruzzi"], genre: "Afrobeats" },
  { title: "Outnumbered", artist: "Dermot Kennedy", genre: "Pop" },
  { title: "Amapiano Hoodlums Mixtape", artist: "DJ Nasty", genre: "DJ Mix" },
  { title: "Amapiano Hits Biri Marung Mix", artist: "DJ Chi", featured: ["Focalistic"], genre: "DJ Mix" },
  { title: "Bomba", artist: "KayGee DaKing", featured: ["Bizizi"], genre: "Amapiano" },
  { title: "I Testify", artist: "Ada Ehi", genre: "Gospel" },
  { title: "A New Day Has Come", artist: "Celine Dion", genre: "Pop" },
  { title: "Only Time (Amapiano)", artist: "Nektunez", featured: ["Enya"], genre: "Amapiano" },
  { title: "Only Time", artist: "Enya", genre: "New Age" },
  { title: "Ameno Amapiano", artist: "Nektunez", genre: "Amapiano" },
  { title: "Only One Shock Absorber", artist: "Time N Gold", genre: "Afrobeats" },
  { title: "Gbe Body", artist: "Adegbodu Twins", genre: "Afrobeats" },
  { title: "Oloruko Arepite", artist: "Sekemi Oluyemi", genre: "Gospel" },
  { title: "Dilika", artist: "KayGee DaKing", featured: ["Bizizi"], genre: "Amapiano" },
  { title: "Inkwari", artist: "KayGee DaKing", featured: ["Bizizi", "Just Bheki", "TNS"], genre: "Amapiano" },
  { title: "Shampopo", artist: "KayGee DaKing", featured: ["Bizizi"], genre: "Amapiano" },
  { title: "Tsa Mandebele 2.0", artist: "KayGeeRsa", featured: ["Mfana Hp"], genre: "Amapiano" },
  { title: "Stance Or Nothing", artist: "KayGeeRsa", featured: ["Sthipla Rsa"], genre: "Amapiano" },
  { title: "Love Infection 2.0", artist: "KayGeeRsa", featured: ["Sthipla Rsa"], genre: "Amapiano" },
  { title: "A Thousand Years", artist: "Christina Perri", genre: "Pop" },
  { title: "Timbolo", artist: "Danny S", featured: ["Oritse Femi"], genre: "Afrobeats" },
  { title: "Higher", artist: "Oritse Femi", featured: ["Iyanya", "Lyta"], genre: "Afrobeats" },
  { title: "Upon Me", artist: "Kizz Daniel", featured: ["Sugarboy"], genre: "Afrobeats" },
  { title: "Idan", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Choke", artist: "Oritse Femi", featured: ["Doctee Pura", "Jaycode", "Resless"], genre: "Afrobeats" },
  { title: "In Efon", artist: "K1 De Ultimate", genre: "Fuji" },
  { title: "Sexy Rosey", artist: "Flavour", genre: "Afrobeats" },
  { title: "Cartel", artist: "Magnito", featured: ["Mark Owi"], genre: "Hip Hop" },
  { title: "Show Me Love", artist: "Yxng A", genre: "Afrobeats" },
  { title: "Love Me Remix", artist: "Global Boy", featured: ["Yxng A"], genre: "Afrobeats" },
  { title: "Kokoma", artist: "K9", genre: "Afrobeats" },
  { title: "Mubaje", artist: "SHAI Abaje", featured: ["Joy Uyo Adejo"], genre: "Afrobeats" },
  { title: "Slow Down", artist: "R2Bees", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Jaiye Jaiye", artist: "Wizkid", featured: ["Femi Kuti"], genre: "Afrobeats" },
  { title: "Mummy Mi", artist: "Wizkid", genre: "Afrobeats" },
  { title: "In My Bed", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Baddest Boy", artist: "EME All Stars", featured: ["Wizkid", "Banky W", "Skales"], genre: "Afrobeats" },
  { title: "Olohun Ojee", artist: "Pasuma", featured: ["Qdot"], genre: "Fuji" },
  { title: "Omo Ologo", artist: "Pasuma", featured: ["Qdot"], genre: "Fuji" },
  { title: "Naija Throwback Old School Mix", artist: "DJ Spark", featured: ["Wizkid", "Davido", "P-Square"], genre: "DJ Mix" },
  { title: "Electro Deep House Mix 2021", artist: "DJ ChrisToSs", featured: ["Alan Walker"], genre: "DJ Mix" },
  { title: "Play", artist: "Alan Walker", featured: ["K-391"], genre: "Electronic" },
  { title: "Someone You Loved", artist: "Lewis Capaldi", genre: "Pop" },
  { title: "Toma Toma", artist: "Ruger", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Logba", artist: "Tml Vibez", featured: ["DJ 4kerty", "Kashcoming"], genre: "Afrobeats" },
  { title: "Pano Tona", artist: "Kizz Daniel", featured: ["Adekunle Gold"], genre: "Afrobeats" },
  { title: "Beautiful", artist: "Akon", genre: "R&B" },
  { title: "You Go Wait", artist: "Demmie Vee", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Question", artist: "Burna Boy", featured: ["Don Jazzy"], genre: "Afrobeats" },
  { title: "Unity", artist: "Alan Walker", genre: "Electronic" },
  { title: "Rhythm & Blues", artist: "Ayra Starr", genre: "Afrobeats" },
  { title: "Mukulu", artist: "Skales", genre: "Afrobeats" },
  { title: "Ase", artist: "Bella Shmurda", genre: "Afrobeats" },
  { title: "Are You There", artist: "Ayo Maff", genre: "Afrobeats" },
  { title: "Aii", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "For You", artist: "Kizz Daniel", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Side Chick", artist: "Kizz Daniel", featured: ["DJ Big N", "Yemi Alade", "Young Jonn"], genre: "Afrobeats" },
  { title: "Yapa", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "No Think Am Remix", artist: "Flektaman", featured: ["Patoranking"], genre: "Afrobeats" },
  { title: "Burn", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Omo Alhaji", artist: "Ycee", genre: "Afrobeats" },
  { title: "Durosoke", artist: "Olamide", genre: "Afrobeats" },
  { title: "Thank God For Me", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Digii IV", artist: "Mr Tee", featured: ["Joshua Baraka", "Tenorboy"], genre: "Afrobeats" },
  { title: "Pikkewyne Remix", artist: "Mega", featured: ["Chakie", "Naiidy"], genre: "Afrobeats" },
  { title: "Never Be The Same", artist: "Camila Cabello", genre: "Pop" },
  { title: "Tere", artist: "Kizz Daniel", featured: ["Diamond Platnumz"], genre: "Afrobeats" },
  { title: "Bolanle", artist: "IVD", featured: ["Zlatan"], genre: "Afrobeats" },
  { title: "Personally", artist: "P-Square", genre: "Afrobeats" },
  { title: "Alingo", artist: "P-Square", genre: "Afrobeats" },
  { title: "Amazing Grace", artist: "Oritse Femi", genre: "Gospel" },
  { title: "Wild Is Life", artist: "Daniel Deuschle", genre: "Pop" },
  { title: "Fine Fine Love", artist: "J. Martins", genre: "Afrobeats" },
  { title: "Wedding Day", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Worship Rendition 2024 Mix", artist: "DJ Amacoz", featured: ["Sunmisola Agbebi", "Grace Idowu"], genre: "DJ Mix" },
  { title: "Sugbon Kan Be Laye Mi", artist: "Femilevite", featured: ["Bola Are"], genre: "Gospel" },
  { title: "Kautaka", artist: "Jaivah", featured: ["King Tone SA"], genre: "Amapiano" },
  { title: "Casanova", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "Omo", artist: "Shadykarz", genre: "Afrobeats" },
  { title: "Yeye Boyfriend", artist: "Zlatan", genre: "Afrobeats" },
  { title: "Alanta", artist: "Nico Gravity", genre: "Afrobeats" },
  { title: "Dapada", artist: "Kimiranking", genre: "Afrobeats" },
  { title: "Sanwo Mi", artist: "King Soundboi", genre: "Afrobeats" },
  { title: "Testimony", artist: "Bhadboi OML", genre: "Afrobeats" },
  { title: "Shayo", artist: "Bigiano", genre: "Afrobeats" },
  { title: "Perfect Gentleman", artist: "Sean Tizzle", genre: "Afrobeats" },
  { title: "Fi Kan We Kan", artist: "BNXN", featured: ["Rema"], genre: "Afrobeats" },
  { title: "Dumalana", artist: "Vee Mampeezy", featured: ["Dr Tawanda"], genre: "Afrobeats" },
  { title: "Omo Ogun", artist: "Shanigbo", genre: "Afrobeats" },
  { title: "Oba Atayero", artist: "Labisi", genre: "Gospel" },
  { title: "Aileyipada", artist: "Sunmisola Agbebi", genre: "Gospel" },
  { title: "Komasava Remix", artist: "Diamond Platnumz", featured: ["Jason Derulo", "Khalil Harrison", "Chley"], genre: "Afrobeats" },
  { title: "Hero", artist: "Enrique Iglesias", genre: "Pop" },
  { title: "Greatest", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Runmo", artist: "Oritse Femi", genre: "Afrobeats" },
  { title: "Opor", artist: "Lil Kesh", featured: ["Naira Marley"], genre: "Afrobeats" },
  { title: "Jump Am Pass", artist: "Terry G", genre: "Afrobeats" },
  { title: "Baby Don't Go", artist: "Terry G", genre: "Afrobeats" },
  { title: "My Darling", artist: "Tiwa Savage", genre: "Afrobeats" },
  { title: "My Baby", artist: "Diamond Platnumz", featured: ["Chike"], genre: "Afrobeats" },
  { title: "Vula Sekele", artist: "Harry Cane", featured: ["Eemoh"], genre: "Amapiano" },
  { title: "Waya Waya", artist: "Master KG", featured: ["Team Mosha"], genre: "Amapiano" },
  { title: "Malwedhe", artist: "King Monada", genre: "Afrobeats" },
  { title: "Chiwana", artist: "King Monada", genre: "Afrobeats" },
  { title: "Back To My Roots", artist: "Lucky Dube", genre: "Reggae" },
  { title: "Action", artist: "Pasuma", featured: ["Olamide"], genre: "Fuji" },
  { title: "Ogo Cele", artist: "Portable", genre: "Afrobeats" },
  { title: "Marhaba", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Romeo Must Die", artist: "Ruger", featured: ["BNXN"], genre: "Afrobeats" },
  { title: "Cry", artist: "Majeeed", featured: ["Lojay"], genre: "Afrobeats" },
  { title: "Way Back", artist: "Khaid", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "My Dealer Remix", artist: "Kaestyle", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Alabarin", artist: "Tope Alabi", genre: "Gospel" },
  { title: "Story For The Gods", artist: "Olamide", genre: "Afrobeats" },
  { title: "Ibadi", artist: "DJ Kamol", featured: ["Olamide", "Lace", "Slyde"], genre: "Afrobeats" },
  { title: "Awuyewuye", artist: "Diamond Jimma", genre: "Afrobeats" },
  { title: "Decided", artist: "Diamond Jimma", genre: "Afrobeats" },
  { title: "Wad Up", artist: "Wizkid", featured: ["D'Prince"], genre: "Afrobeats" },
  { title: "Holla At Your Boy", artist: "Wizkid", genre: "Afrobeats" },
  { title: "For Me", artist: "Wizkid", featured: ["Wande Coal"], genre: "Afrobeats" },
  { title: "What You Wanna Do", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Eme Boyz", artist: "Wizkid", featured: ["Skales", "Banky W"], genre: "Afrobeats" },
  { title: "Tease Me", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Don't Dull", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Oluwa Lo Ni", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Oriade Remix", artist: "Portable", featured: ["Wizkid", "Davido"], genre: "Afrobeats" },
  { title: "Sexy Ladies", artist: "Timaya", genre: "Afrobeats" },
  { title: "Malonogede", artist: "Timaya", featured: ["Terry G"], genre: "Afrobeats" },
  { title: "Azaman", artist: "Rema", genre: "Afrobeats" },
  { title: "Run Mad", artist: "Terry G", genre: "Afrobeats" },
  { title: "Shout Out", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Playlist Mix 2.0", artist: "DJ Alinco", genre: "DJ Mix" },
  { title: "Chiller Hype Mix", artist: "DJ Vodka", featured: ["Dagfela"], genre: "DJ Mix" },
  { title: "POE", artist: "Ruger", featured: ["BNXN"], genre: "Afrobeats" },
  { title: "Men Are Crazy", artist: "Simi", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Slow Whine", artist: "Wizkid", featured: ["Banky W"], genre: "Afrobeats" },
  { title: "Pakurumo", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Scatter The Floor", artist: "Wizkid", genre: "Afrobeats" },
  { title: "No Lele", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Say My Name", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Gidi Girl", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Girl", artist: "Bracket", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Sexy Mama", artist: "Iyanya", featured: ["Wizkid"], genre: "Afrobeats" },
  { title: "Final Baba Nla", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Celebrate", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Thank You", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Joy", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Street Credibility", artist: "9ice", featured: ["2Baba"], genre: "Afrobeats" },
  { title: "Mapariwo", artist: "Zinoleesky", genre: "Afrobeats" },
  { title: "Your Toto Cruise", artist: "DJ YK Mule", genre: "Afrobeats" },
  { title: "Xtra Cool", artist: "Young Jonn", genre: "Afrobeats" },
  { title: "You The Boss", artist: "Rick Ross", featured: ["Nicki Minaj"], genre: "Hip Hop" },
  { title: "You Know", artist: "Small Doctor", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Yanga", artist: "Chidinma", genre: "Afrobeats" },
  { title: "Yahooze", artist: "Olu Maintain", genre: "Afrobeats" },
  { title: "Kosoluwa Laye", artist: "Toluwani Sings", genre: "Gospel" },
  { title: "World", artist: "Stone D", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Work Around", artist: "Lanre Teriba", featured: ["Oritse Femi", "Iblaze"], genre: "Afrobeats" },
  { title: "Won Do Iyawo", artist: "DJ Styles", featured: ["Portable"], genre: "Afrobeats" },
  { title: "You Go Kill Me Remix", artist: "Sarkodie", featured: ["E.L", "Ice Prince", "Navio", "Wizkid"], genre: "Afrobeats" },
  { title: "You Dey Whine Me", artist: "Austine Emmanuel", genre: "Afrobeats" },
  { title: "You Bad", artist: "Wande Coal", genre: "Afrobeats" },
  { title: "Yoruba Worship Medley", artist: "Dare Justified", genre: "Gospel" },
  { title: "Yemi My Lover", artist: "Olamide", genre: "Afrobeats" },
  { title: "Yawa", artist: "Fireboy DML", genre: "Afrobeats" },
  { title: "Waloda", artist: "Lil Frosh", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Wassup Dance", artist: "DJ YK Mule", featured: ["GMG Boss"], genre: "Afrobeats" },
  { title: "Walking Dead", artist: "Ayox", featured: ["Zlatan"], genre: "Afrobeats" },
  { title: "Wale", artist: "Candy Bleakz", genre: "Afrobeats" },
  { title: "Wake Up", artist: "Flavour", featured: ["Wande Coal"], genre: "Afrobeats" },
  { title: "Wait", artist: "Teni", genre: "Afrobeats" },
  { title: "Wait For Me", artist: "Johnny Drille", genre: "Afrobeats" },
  { title: "Why", artist: "Naira Marley", genre: "Afrobeats" },
  { title: "Won Yabo", artist: "Rexxie", featured: ["Lil Frosh"], genre: "Afrobeats" },
  { title: "Won Da Mo", artist: "Mavins", featured: ["Rema", "Ayra Starr", "Ladipoe", "Crayon"], genre: "Afrobeats" },
  { title: "Woman", artist: "Omah Lay", genre: "Afrobeats" },
  { title: "Woju", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Wishlist", artist: "Jaywillz", genre: "Afrobeats" },
  { title: "Superstar", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Who You Epp", artist: "Olamide", featured: ["Chinko Ekun"], genre: "Afrobeats" },
  { title: "Where I'm From", artist: "Tml Vibez", featured: ["Seyi Vibez"], genre: "Afrobeats" },
  { title: "Wells Fargo", artist: "Vibez Inc", featured: ["Tml Vibez"], genre: "Afrobeats" },
  { title: "Weekend", artist: "Mohbad", featured: ["Imole"], genre: "Afrobeats" },
  { title: "Way Maker", artist: "Sinach", genre: "Gospel" },
  { title: "Wave", artist: "Asake", featured: ["Central Cee"], genre: "Afrobeats" },
  { title: "Water", artist: "Tyla", genre: "Amapiano" },
  { title: "Soweto", artist: "Victony", featured: ["Tempoe"], genre: "Afrobeats" },
  { title: "Very Sad", artist: "Enchan", genre: "Afrobeats" },
  { title: "Vanilla", artist: "Burna Boy", genre: "Afrobeats" },
  { title: "Vanilla Bottega", artist: "Lil Kesh", featured: ["Joeboy"], genre: "Afrobeats" },
  { title: "Up And Down", artist: "Richfame", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Umbrella", artist: "Nasboi", featured: ["Wande Coal"], genre: "Afrobeats" },
  { title: "UOK", artist: "Nasty C", genre: "Hip Hop" },
  { title: "Touchin Body", artist: "J. Martins", featured: ["DJ Arafat"], genre: "Afrobeats" },
  { title: "Too Correct", artist: "Crayon", featured: ["Rema"], genre: "Afrobeats" },
  { title: "Too Busy To Be Bae", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "U", artist: "Davido", featured: ["Skepta"], genre: "Afrobeats" },
  { title: "The Real MVP", artist: "Olamide", genre: "Afrobeats" },
  { title: "Twe Twe Remix", artist: "Kizz Daniel", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Try", artist: "TI Blaze", genre: "Afrobeats" },
  { title: "Trouble Maker", artist: "Rema", genre: "Afrobeats" },
  { title: "Trending", artist: "Muyeez", featured: ["Tml Vibez"], genre: "Afrobeats" },
  { title: "Trenches", artist: "Skiibii", genre: "Afrobeats" },
  { title: "Sweet As E Be", artist: "Remy Crown", featured: ["Kizz Daniel"], genre: "Afrobeats" },
  { title: "Sunshine", artist: "Asake", genre: "Afrobeats" },
  { title: "Summer Body", artist: "Olamide", featured: ["Davido"], genre: "Afrobeats" },
  { title: "Sugar Mama", artist: "Joeboy", genre: "Afrobeats" },
  { title: "Suddenly", artist: "Seyi Vibez", featured: ["Young Jonn"], genre: "Afrobeats" },
  { title: "Street Mix 3 2024", artist: "DJ Lawy", genre: "DJ Mix" },
  { title: "Street Love", artist: "Olamide", featured: ["Minus2"], genre: "Afrobeats" },
  { title: "Jaiye Foreign", artist: "Tiwa Savage", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Time", artist: "Lyta", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Tiff", artist: "May D", genre: "Afrobeats" },
  { title: "Faith", artist: "The Weeknd", genre: "R&B" },
  { title: "The Best", artist: "Davido", featured: ["Mayorkun"], genre: "Afrobeats" },
  { title: "Thank You For Saving Me", artist: "Voice Of The Cross", genre: "Gospel" },
  { title: "Injure Me", artist: "Teni", genre: "Afrobeats" },
  { title: "Tambolo", artist: "Portable", genre: "Afrobeats" },
  { title: "Street Credibility", artist: "DJ OP Dot", featured: ["Seyi Vibez", "Ajesings"], genre: "Afrobeats" },
  { title: "State And Capital", artist: "DJ Baddo", featured: ["Hypeman Big Blaq"], genre: "Afrobeats" },
  { title: "Standing Ovation", artist: "Tiwa Savage", featured: ["Olamide"], genre: "Afrobeats" },
  { title: "Who Is Your Guy", artist: "Spyro", genre: "Afrobeats" },
  { title: "Speak To Me", artist: "Reekado Banks", featured: ["Tiwa Savage"], genre: "Afrobeats" },
  { title: "Sorry", artist: "Mohbad", genre: "Afrobeats" },
  { title: "Skin", artist: "Kizz Daniel", featured: ["Kelvyn Colt"], genre: "Afrobeats" },
  { title: "Skelemba", artist: "Olamide", featured: ["Don Jazzy"], genre: "Afrobeats" },
  { title: "Sisi Nene", artist: "Wizkid", genre: "Afrobeats" },
  { title: "Shu-Peru", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Showa", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "Show Your Style", artist: "Sabi", genre: "Afrobeats" },
  { title: "Shoki Remix", artist: "Lil Kesh", featured: ["Davido", "Olamide"], genre: "Afrobeats" },
  { title: "Sorry Blame It On Me", artist: "Akon", genre: "R&B" },
  { title: "Sola", artist: "Tkinzy", featured: ["Teni"], genre: "Afrobeats" },
  { title: "Sokoto", artist: "Minz", featured: ["Zinoleesky"], genre: "Afrobeats" },
  { title: "Sofa", artist: "Kizz Daniel", genre: "Afrobeats" },
  { title: "So Cold", artist: "Bella Shmurda", featured: ["Popcaan"], genre: "Afrobeats" },
  { title: "Snapchat", artist: "Ruger", genre: "Afrobeats" },
];

export interface CuratedSongHit extends CuratedSong {
  score: number;
}

function normalize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9\s.']/g, " ").replace(/\s+/g, " ").trim();
}

export function searchCuratedSongs(query: string, limit = 24): CuratedSongHit[] {
  const q = normalize(query);
  if (!q || q.length < 2) return [];

  const hits: CuratedSongHit[] = [];

  for (const song of curatedLibrarySongs) {
    const title = normalize(song.title);
    const artist = normalize(song.artist);
    const featured = (song.featured || []).map(normalize).join(" ");
    const blob = `${title} ${artist} ${featured}`;
    let score = 0;

    if (title === q || artist === q) score = 100;
    else if (title.startsWith(q) || artist.startsWith(q)) score = 85;
    else if (title.includes(q) || artist.includes(q) || blob.includes(q)) score = 70;
    else {
      const tokens = q.split(" ").filter(Boolean);
      if (tokens.length > 1 && tokens.every((t) => blob.includes(t))) score = 55;
      else if (tokens.some((t) => t.length > 2 && blob.includes(t))) score = 30;
    }

    if (score > 0) hits.push({ ...song, score });
  }

  return hits.sort((a, b) => b.score - a.score || a.title.localeCompare(b.title)).slice(0, limit);
}

export function getCuratedSongsForArtist(artistName: string): CuratedSong[] {
  const n = normalize(artistName);
  if (!n) return [];
  return curatedLibrarySongs.filter((song) => {
    if (normalize(song.artist) === n) return true;
    return (song.featured || []).some((f) => normalize(f) === n);
  });
}
