export type CuratedCountryId =
  | "nigeria"
  | "usa"
  | "uk"
  | "india"
  | "south_korea"
  | "china"
  | "japan"
  | "ghana"
  | "south_africa"
  | "gospel"
  | "djs";

export interface CuratedCountry {
  id: CuratedCountryId;
  name: string;
  flag: string;
  blurb: string;
  artists: string[];
}

/** Curated discovery directory (names only). Playback still comes from a legal provider. */
export const curatedCountries: CuratedCountry[] = [
  {
    id: "nigeria",
    name: "Nigeria",
    flag: "🇳🇬",
    blurb: "Afrobeats, highlife, fuji, street-hop and Naija classics",
    artists: [
      "Fela Kuti",
      "King Sunny Ade",
      "Ebenezer Obey",
      "Chief Commander Ebenezer Obey",
      "Sir Shina Peters",
      "Wasiu Ayinde",
      "K1 De Ultimate",
      "Pasuma",
      "Saheed Osupa",
      "Ayinla Kollington",
      "Adewale Ayuba",
      "Orlando Owoh",
      "Haruna Ishola",
      "I.K. Dairo",
      "Sunny Ade",
      "Onyeka Onwenu",
      "Christy Essien-Igbokwe",
      "Majek Fashek",
      "Ras Kimono",
      "Alex O",
      "Daddy Showkey",
      "African China",
      "Eedris Abdulkareem",
      "Remedies",
      "Plantation Boyz",
      "2Baba",
      "Blackface",
      "Faze",
      "P-Square",
      "D'banj",
      "Don Jazzy",
      "Wande Coal",
      "Dr SID",
      "D'Prince",
      "Tiwa Savage",
      "Wizkid",
      "Davido",
      "Olamide",
      "Kcee",
      "KCee",
      "Harrysong",
      "Timaya",
      "Duncan Mighty",
      "Flavour",
      "Phyno",
      "Yemi Alade",
      "Seyi Shay",
      "Chidinma",
      "Tekno",
      "Kizz Daniel",
      "Mayorkun",
      "Lil Kesh",
      "Oritse Femi",
      "CDQ",
      "Reminisce",
      "Vector",
      "MI Abaga",
      "Ice Prince",
      "Falz",
      "Skales",
      "Adekunle Gold",
      "Simi",
      "Joeboy",
      "Fireboy DML",
      "Rema",
      "Ayra Starr",
      "BNXN",
      "Oxlade",
      "Asake",
      "Omah Lay",
      "Bella Shmurda",
      "Zinoleesky",
      "Mohbad",
      "Shallipopi",
      "Seyi Vibez",
      "Ruger",
      "Blaqbonez",
      "Odumodublvck",
      "Bloody Civilian",
      "Qing Madi",
      "Fido",
      "Portable",
      "Spyro",
      "Victony",
      "Chike",
      "Tems",
      "Ckay",
      "Patoranking",
      "Zlatan",
      "Naira Marley",
      "Terry G",
      "9ice",
      "Sound Sultan",
      "Young Jonn",
      "Lyta",
      "Brymo",
      "EMO Grae",
      "Remi Aluko",
      "Arbiz",
      "Small Doctor",
      "Barry Jhay",
      "Ladipoe",
      "Di'ja",
      "Khaid",
      "Darkoo",
      "Oyinkanade",
      "Diamond Jimma",
      "Mish",
      "Alimi",
      "Taye Currency",
      "Stone D",
      "Yonda",
      "Esther Oji",
      "G.O.E",
      "Rexxie",
      "Skiibii",
      "Benzola",
      "Figo M",
      "Omawumi",
      "Ayox",
      "Slim Joe",
      "Innoweeny",
      "Solid Star",
      "Iyanya",
      "Carterefe",
      "Berri-Tiga",
      "Boy Spyce",
      "Tml Vibez",
      "Candy Bleakz",
      "DeeBee",
      "Viktoh",
      "May D",
      "Ajuju",
      "Skaliey",
      "Obong Etighi",
      "Demmie Vee",
      "Ayo Maff",
      "Dotman",
      "Qdot",
      "Lummyvibes",
      "Xavior",
      "Kida Kudz",
      "EmmaOMG",
      "Denike",
      "Emma Nyra",
      "Small Baddo",
      "Idowest",
      "Pheelz",
      "Johnny Drille",
      "DOTTi The Deity",
      "Shadykarz",
      "Bracket",
      "Melvitto",
      "Lace",
      "T Dollar",
      "Teni",
      "J. Martins",
      "King Falope",
      "Reekado Banks",
      "Otega",
      "Cheque",
      "Olakira",
      "Pepenazi",
      "Sean Tizzle",
      "Damidrizzy",
      "Aloba Fresh",
      "O Black",
      "King Wadada",
      "EddinzBani",
      "Lord Of Ajasa",
      "Jaywon",
      "Aloma",
      "Laycon",
      "Bad Boy Timz",
      "Fiokee",
      "Jaywillz",
      "Magixx",
      "Crayon",
      "Don Jay",
      "2Kriss",
      "Elmah",
      "MelodyVibes",
      "Muraino",
      "Korede Bello",
      "B Banks",
      "JT Boyz",
      "Yemi Sax",
      "Remy T",
      "Tillaman",
      "CD Wonder",
      "DJ Skipo",
      "Dr Sid",
      "K-Switch",
      "Elizy",
      "Poco Lee",
      "Papayan",
      "Young Al",
      "Balloranking",
      "Super D",
      "Nimix",
      "Fola",
      "Skelvin",
      "B Red",
      "Sellah Malaika",
      "Slattt",
      "Strei",
      "ApreeL",
      "Isat",
      "Monalisa Stephen",
      "Jaycode",
      "Sabi",
      "South Plxya",
      "NerdFnd",
      "Hysaint",
      "Blo",
      "Maleek Berry",
      "Bhadboi OML",
      "Cazulee",
      "Danny S",
      "Babyboy AV",
      "Scope",
      "Rotimikeys",
      "Gbenga Akinfenwa",
      "Rhy Elliot",
      "Shoday",
      "Tmizzy Mrhorrizen",
      "Ya Levis",
      "Hotkid",
      "King Perryy",
      "Majeeed",
      "Kunmie",
      "Mabel",
      "Jonah Lanez",
      "Diamond Platnumz",
      "Aya Nakamura",
      "T.I BLAZE",
      "Terry Apala",
      "Lola Rae",
      "Nasboi",
      "Muyeez",
      "Daecolm",
      "Wizard Chan",
      "Vicoka",
      "King Soundboi",
      "Lanre Teriba",
      "Olawale Imole",
      "Iblaze",
      "Jeleel",
      "Mr Pee",
      "Modupe",
      "Xsmile",
      "Yungskid",
      "Rybeena",
      "Peruzzi",
      "Fresh VDM",
      "Sugarboy",
      "Banky W",
      "Chella",
      "Eroomi",
      "Hotkeed",
      "Young D",
      "BBO",
      "Inayah",
      "Baddy Oosha",
      "Seriki",
      "Fujicologist",
      "Kodee",
      "X Project",
      "Rudy Omoibile",
      "Zerrydl",
      "Jojo Leo",
      "Angelique Kidjo",
      "DJ 4kerty",
      "Mr Eazi",
      "Gingo",
      "MC Galaxy",
      "Lara George",
      "Sauce Kid",
      "Chinko Ekun",
      "Pryme",
      "Styl-Plus",
      "Zule Zoo",
      "Dayo Amusa",
      "Dr Pat",
      "Sheyman",
      "Notch",
      "Dammy Krane",
      "Runtown",
      "Cynthia Morgan",
      "Zealot",
      "Tolibian",
      "Ogoeri",
      "Goke Bajowa",
      "Danfo Drivers",
      "Flyboy INC",
      "Danny Young",
      "Naeto C",
      "Masterkraft",
      "Toofan",
      "Kranium",
      "Emeka Indo",
      "Wizka",
      "Dagrin",
      "Adegbodu Twins",
      "Nektunez",
      "Time N Gold",
      "Femi Kuti",
      "Magnito",
      "Kashcoming",
      "K9",
      "Yxng A",
      "Global Boy",
      "SHAI Abaje",
      "EME All Stars",
      "Ycee",
      "Flektaman",
      "Bigiano",
      "IVD",
      "Nico Gravity",
      "Kimiranking",
      "Femilevite",
      "Labisi",
      "Shanigbo",
      "Kaestyle",
      "DJ Kamol",
      "Saint Janet",
      "Olu Maintain",
      "Lil Frosh",
      "DJ Styles",
      "Austine Emmanuel",
      "Vibez Inc",
      "TI Blaze",
      "Remy Crown",
      "Enchan",
      "Richfame",
      "Mavins",
      "Minz",
      "Tkinzy",
    ],
  },
  {
    id: "usa",
    name: "United States",
    flag: "🇺🇸",
    blurb: "Pop, hip-hop, R&B, country and American classics",
    artists: [
      "Michael Jackson",
      "Janet Jackson",
      "Prince",
      "Madonna",
      "Whitney Houston",
      "Mariah Carey",
      "Beyoncé",
      "Jay-Z",
      "Kanye West",
      "Kendrick Lamar",
      "J. Cole",
      "Drake",
      "Nicki Minaj",
      "Cardi B",
      "Megan Thee Stallion",
      "Doja Cat",
      "Ice Spice",
      "Eminem",
      "50 Cent",
      "Snoop Dogg",
      "Dr. Dre",
      "Tupac Shakur",
      "The Notorious B.I.G.",
      "Nas",
      "Lil Wayne",
      "Birdman",
      "Rick Ross",
      "Meek Mill",
      "Future",
      "Young Thug",
      "Gunna",
      "Lil Baby",
      "DaBaby",
      "Roddy Ricch",
      "Polo G",
      "Juice WRLD",
      "Pop Smoke",
      "XXXTentacion",
      "Trippie Redd",
      "Kodak Black",
      "NLE Choppa",
      "Chief Keef",
      "Lil Durk",
      "G Herbo",
      "A Boogie wit da Hoodie",
      "21 Savage",
      "Offset",
      "Quavo",
      "Takeoff",
      "Migos",
      "Travis Scott",
      "Playboi Carti",
      "Tyler, the Creator",
      "A$AP Rocky",
      "A$AP Ferg",
      "Pusha T",
      "Logic",
      "Joyner Lucas",
      "Tech N9ne",
      "Busta Rhymes",
      "Missy Elliott",
      "Lil Kim",
      "Queen Latifah",
      "Eve",
      "Salt-N-Pepa",
      "LL Cool J",
      "DMX",
      "Ja Rule",
      "Nelly",
      "T.I.",
      "Ludacris",
      "Akon",
      "Austin Mahone",
      "T-Pain",
      "Ne-Yo",
      "Usher",
      "Chris Brown",
      "Fridayy",
      "Jason Derulo",
      "Bruno Mars",
      "Anderson .Paak",
      "Alicia Keys",
      "John Legend",
      "H.E.R.",
      "SZA",
      "Summer Walker",
      "Kehlani",
      "Ella Mai",
      "Ariana Grande",
      "Billie Eilish",
      "Olivia Rodrigo",
      "Selena Gomez",
      "Demi Lovato",
      "Miley Cyrus",
      "Sabrina Carpenter",
      "Tate McRae",
      "Camila Cabello",
      "Jennifer Lopez",
      "Christina Aguilera",
      "Britney Spears",
      "Pink",
      "Kelly Clarkson",
      "Katy Perry",
      "Taylor Swift",
      "Lady Gaga",
      "Lana Del Rey",
      "Gwen Stefani",
      "Avril Lavigne",
      "Cyndi Lauper",
      "Tina Turner",
      "Diana Ross",
      "Stevie Wonder",
      "Lionel Richie",
      "Marvin Gaye",
      "Ray Charles",
      "Elvis Presley",
      "Frank Sinatra",
      "Bob Dylan",
      "Bruce Springsteen",
      "Bon Jovi",
      "Jon Bon Jovi",
      "Billy Joel",
      "Billy Ray Cyrus",
      "Dolly Parton",
      "Johnny Cash",
      "Willie Nelson",
      "Luke Combs",
      "Morgan Wallen",
      "Carrie Underwood",
      "Kacey Musgraves",
      "Shania Twain",
      "Post Malone",
      "Machine Gun Kelly",
      "Jack Harlow",
      "Ty Dolla $ign",
      "Tyga",
      "Wiz Khalifa",
      "Lil Tjay",
      "J.I the Prince of N.Y",
      "Zoe Wees",
      "Winona Oak",
      "Young Jeezy",
      "Jeleel",
      "Feid",
      "Tatiana Manaois",
      "Rosa Linn",
      "Inayah",
      "Halsey",
      "Rod Wave",
      "Sean Kingston",
      "Justin Bieber",
      "Christina Perri",
      "Alan Walker",
      "Disturbed",
      "Major Lazer",
      "Celine Dion",
      "Enrique Iglesias",
      "The Weeknd",
    ],
  },
  {
    id: "uk",
    name: "United Kingdom",
    flag: "🇬🇧",
    blurb: "UK pop, rock, grime and British legends",
    artists: [
      "Ed Sheeran",
      "Dermot Kennedy",
      "Enya",
      "Adele",
      "Dua Lipa",
      "Harry Styles",
      "Elton John",
      "Sam Smith",
      "George Michael",
      "David Bowie",
      "Freddie Mercury",
      "Queen",
      "The Beatles",
      "John Lennon",
      "Paul McCartney",
      "George Harrison",
      "Ringo Starr",
      "Mick Jagger",
      "Keith Richards",
      "The Rolling Stones",
      "Coldplay",
      "Chris Martin",
      "Oasis",
      "Liam Gallagher",
      "Noel Gallagher",
      "Blur",
      "Gorillaz",
      "Robbie Williams",
      "Take That",
      "One Direction",
      "Zayn Malik",
      "Louis Tomlinson",
      "Niall Horan",
      "Liam Payne",
      "Rita Ora",
      "Jessie J",
      "Leona Lewis",
      "Ellie Goulding",
      "Anne-Marie",
      "Raye",
      "Little Mix",
      "Jesy Nelson",
      "Perrie Edwards",
      "Jade Thirlwall",
      "Leigh-Anne Pinnock",
      "Cheryl",
      "Girls Aloud",
      "Amy Winehouse",
      "Florence + The Machine",
      "Florence Welch",
      "Lewis Capaldi",
      "Calvin Harris",
      "DJ Snake",
      "James Arthur",
      "Tom Grennan",
      "Craig David",
      "Taio Cruz",
      "Labrinth",
      "Stormzy",
      "Skepta",
      "Dave",
      "Central Cee",
      "Aitch",
      "Digga D",
      "Headie One",
      "Tion Wayne",
      "AJ Tracey",
      "Chip",
      "Dizzee Rascal",
      "Wiley",
      "Tinie Tempah",
      "Mabel",
      "Emeli Sandé",
      "Seal",
      "Rod Stewart",
      "Phil Collins",
      "Genesis",
      "Eric Clapton",
      "Sting",
      "The Police",
      "Pet Shop Boys",
      "Duran Duran",
      "Depeche Mode",
      "The Cure",
      "Radiohead",
      "Arctic Monkeys",
      "Kasabian",
      "Muse",
      "The Smiths",
      "Morrissey",
      "Bananarama",
      "Spice Girls",
      "Geri Halliwell",
      "Emma Bunton",
      "Mel B",
      "Mel C",
      "Victoria Beckham",
      "Simply Red",
      "UB40",
      "Culture Club",
      "Boy George",
      "Def Leppard",
      "Iron Maiden",
      "Black Sabbath",
      "Ozzy Osbourne",
      "Judas Priest",
      "Motörhead",
      "The Kinks",
      "Bee Gees",
      "Clean Bandit",
      "Rudimental",
      "Sigala",
      "Joel Corry",
      "Jax Jones",
      "Becky Hill",
      "Example",
      "Paloma Faith",
      "Passenger",
      "James Blunt",
    ],
  },
  {
    id: "india",
    name: "India",
    flag: "🇮🇳",
    blurb: "Bollywood, Punjabi, and Indian playback stars",
    artists: [
      "Arijit Singh",
      "Shreya Ghoshal",
      "Sonu Nigam",
      "A. R. Rahman",
      "Lata Mangeshkar",
      "Kishore Kumar",
      "Mohammed Rafi",
      "Udit Narayan",
      "Kumar Sanu",
      "Alka Yagnik",
      "Neha Kakkar",
      "Jubin Nautiyal",
      "Badshah",
      "Yo Yo Honey Singh",
      "Diljit Dosanjh",
      "Guru Randhawa",
      "AP Dhillon",
      "Karan Aujla",
      "Sidhu Moose Wala",
      "Harrdy Sandhu",
      "B Praak",
      "Darshan Raval",
      "Armaan Malik",
      "Vishal Dadlani",
      "Shekhar Ravjiani",
      "Sunidhi Chauhan",
      "Monali Thakur",
      "Kanika Kapoor",
      "Neeti Mohan",
      "Ankit Tiwari",
      "Mika Singh",
      "Shaan",
      "KK",
      "Sukhwinder Singh",
      "Himesh Reshammiya",
      "Daler Mehndi",
      "Kailash Kher",
      "Lucky Ali",
      "Pritam",
      "Amit Trivedi",
      "Anirudh Ravichander",
      "Devi Sri Prasad",
      "Ilaiyaraaja",
      "Shankar Mahadevan",
      "Hariharan",
      "K. S. Chithra",
      "S. P. Balasubrahmanyam",
      "K. J. Yesudas",
      "Mohit Chauhan",
      "Palak Muchhal",
      "Asees Kaur",
    ],
  },
  {
    id: "south_korea",
    name: "South Korea",
    flag: "🇰🇷",
    blurb: "K-pop groups, soloists and idols",
    artists: [
      "BTS",
      "RM",
      "Jin",
      "Suga",
      "J-Hope",
      "Jimin",
      "V",
      "Jungkook",
      "BLACKPINK",
      "Jisoo",
      "Jennie",
      "Rosé",
      "Lisa",
      "PSY",
      "IU",
      "EXO",
      "Baekhyun",
      "Chen",
      "D.O.",
      "Kai",
      "Suho",
      "Chanyeol",
      "Sehun",
      "Xiumin",
      "TWICE",
      "Nayeon",
      "Jeongyeon",
      "Momo",
      "Sana",
      "Jihyo",
      "Mina",
      "Dahyun",
      "Chaeyoung",
      "Tzuyu",
      "SEVENTEEN",
      "Stray Kids",
      "NewJeans",
      "ATEEZ",
      "BIGBANG",
      "G-Dragon",
      "Taeyang",
      "Daesung",
      "T.O.P",
      "Red Velvet",
      "Girls' Generation",
      "Taeyeon",
      "SHINee",
      "Taemin",
      "Super Junior",
      "TVXQ",
      "MONSTA X",
      "ITZY",
      "aespa",
      "ENHYPEN",
      "TXT",
      "NCT 127",
      "NCT Dream",
      "ZEROBASEONE",
      "BABYMONSTER",
      "IVE",
      "LE SSERAFIM",
      "(G)I-DLE",
      "MAMAMOO",
    ],
  },
  {
    id: "china",
    name: "China",
    flag: "🇨🇳",
    blurb: "Mandopop and Chinese popular artists",
    artists: [
      "Jay Chou",
      "Jackson Wang",
      "G.E.M.",
      "Lay Zhang",
      "Kris Wu",
      "Hua Chenyu",
      "Jane Zhang",
      "Joker Xue",
      "Wang Leehom",
      "Jolin Tsai",
      "Stefanie Sun",
      "Faye Wong",
      "Lexie Liu",
      "Tia Ray",
      "Tan Weiwei",
      "Sa Dingding",
      "Han Hong",
      "Xu Song",
      "JJ Lin",
      "David Tao",
      "Angela Zhang",
      "Hebe Tien",
      "Ella Chen",
      "Selina Jen",
      "Richie Jen",
      "Li Yuchun",
      "Wang Feng",
      "Pu Shu",
      "Eason Chan",
      "Teresa Teng",
    ],
  },
  {
    id: "japan",
    name: "Japan",
    flag: "🇯🇵",
    blurb: "J-pop, rock and Japanese chart artists",
    artists: [
      "Hikaru Utada",
      "YOASOBI",
      "Ado",
      "Kenshi Yonezu",
      "LiSA",
      "King Gnu",
      "Official HIGE DANDism",
      "ONE OK ROCK",
      "BABYMETAL",
      "X Japan",
      "B'z",
      "Arashi",
      "SMAP",
      "Namie Amuro",
      "Ayumi Hamasaki",
      "AKB48",
      "Nogizaka46",
      "Perfume",
      "Radwimps",
      "Mrs. GREEN APPLE",
      "SEKAI NO OWARI",
      "Mr. Children",
      "Southern All Stars",
      "YUI",
      "Aimyon",
      "DA PUMP",
      "EXILE",
      "GENERATIONS",
      "Daichi Miura",
      "Mika Nakashima",
    ],
  },
  {
    id: "ghana",
    name: "Ghana",
    flag: "🇬🇭",
    blurb: "Hiplife, dancehall and Ghanaian stars",
    artists: [
      "Sarkodie",
      "Toofan",
      "Stonebwoy",
      "Shatta Wale",
      "Black Sherif",
      "King Promise",
      "KiDi",
      "Kuami Eugene",
      "Samini",
      "Mzbel",
      "Efya",
      "Wendy Shay",
      "Fameye",
      "Amerado",
      "Strongman",
      "Medikal",
      "Joey B",
      "E.L",
      "D-Black",
      "M.anifest",
      "Gyakie",
      "Camidoh",
      "Kofi Kinaata",
      "Okyeame Kwame",
      "Kwesi Arthur",
      "Reggie Rockstone",
      "Obrafour",
      "Castro",
      "Akwaboah",
      "Adina",
      "Becca",
      "Kaakie",
      "R2Bees",
    ],
  },
  {
    id: "south_africa",
    name: "South Africa",
    flag: "🇿🇦",
    blurb: "Amapiano, Afro-house and South African hits",
    artists: [
      "Tyla",
      "Black Coffee",
      "Master KG",
      "DJ Maphorisa",
      "Kabza De Small",
      "Makhadzi",
      "Cassper Nyovest",
      "AKA",
      "Nasty C",
      "K.O",
      "Kwesta",
      "A-Reece",
      "Focalistic",
      "Young Stunna",
      "Musa Keys",
      "Zakes Bantwini",
      "Sha Sha",
      "Prince Kaybee",
      "Sun-EL Musician",
      "Heavy K",
      "DJ Tira",
      "Big Zulu",
      "Emtee",
      "Lady Zamar",
      "Brenda Fassie",
      "Miriam Makeba",
      "Hugh Masekela",
      "Zahara",
      "Mafikizolo",
      "TitoM",
      "Yuppe",
      "S.N.E",
      "Blaq Diamond",
      "Felo Le Tee",
      "Myztro",
      "Daliwonga",
      "Skavenja",
      "Sfear Nofokol",
      "Lucky Dube",
      "Harry Cane",
      "Teejay",
      "Ntando Yamahlubi",
      "Al Xapo",
      "Soa Mattrix",
      "Wanitwa Mos",
      "Sando Cynthia",
      "Dr Tawanda",
      "Nelcy B",
      "Uncle Waffles",
      "Tony Duardo",
      "Justin99",
      "Pcee",
      "EeQue",
      "Goon Flavour",
      "Eemoh",
      "Tebza De DJ",
      "DJ Nomza The King",
      "The Lowkeys",
      "Thuto The Human",
      "Major Keys",
      "Tyler ICU",
      "Uhuru",
      "DJ Tira",
      "King Temoso",
      "Nkosazana Daughter",
      "Nobuhle",
      "Sfisoman",
      "HBK Live Act",
      "Khalil Harrison",
      "KayGee DaKing",
      "KayGeeRsa",
      "Bizizi",
      "Jaivah",
      "Vee Mampeezy",
      "Daniel Deuschle",
      "King Monada",
    ],
  },
  {
    id: "gospel",
    name: "Gospel",
    flag: "✝️",
    blurb: "Gospel and worship artists",
    artists: [
      "Nathaniel Bassey",
      "Mercy Chinwo",
      "Sinach",
      "Frank Edwards",
      "Eben",
      "Moses Bliss",
      "Dunsin Oyekan",
      "Tim Godfrey",
      "Ada Ehi",
      "Steve Crown",
      "Tope Alabi",
      "Sunmisola Agbebi",
      "Bidemi Olaoba",
      "Elijah Akintunde",
      "Toluwani Sings",
      "Minister Oluwaferanmi",
      "Shola Allyson",
      "Lawrence Oyor",
      "Theophilus Sunday",
      "Esther Oji",
      "Judikay",
      "Ajuju",
      "Victoria Orenze",
      "EmmaOMG",
      "Dare David",
      "Ayo Ajewole",
      "Chandler Moore",
      "Odunayo Akintomide",
      "Agatha Moses",
      "Bisimanuel",
      "Nexarito",
      "Jesukayode",
      "Premium Emf",
      "Delana Hope",
      "Dickson Mwita",
      "Keenan Te",
      "The Blue Collar Believer",
      "Hillsong Worship",
      "Testimony Jaga",
      "Uchenna Okereke",
      "Pelumi Deborah",
      "Jonathan Hutcherson",
      "Varisha Shakila",
      "My God",
      "Yinka Okeleye",
      "Ameenat Ajao",
      "Bola Are",
      "Emeka Indo",
      "Sekemi Oluyemi",
      "Femilevite",
      "Labisi",
      "Steady Worship",
      "Dare Justified",
      "Voice Of The Cross",
    ],
  },
  {
    id: "djs",
    name: "DJs Worldwide",
    flag: "🎧",
    blurb: "DJs and mix selectors across regions",
    artists: [
      "DJ XOD",
      "DJ Doublesoud",
      "DJ Tymix",
      "DJ Selex",
      "DJ Zeez",
      "DJ Worldwide",
      "DJ Speeddo",
      "DJ S Boy",
      "DJ Neptune",
      "DJ Spinall",
      "DJ Consequence",
      "DJ Kaywise",
      "DJ Jimmy Jatt",
      "DJ Cuppy",
      "DJ Xclusive",
      "DJ Baddo",
      "DJ YK Mule",
      "DJ Amacoz",
      "DJ Clevan",
      "DJ Nice Originator",
      "DJ Nasty",
      "DJ Fizzy",
      "DJ Spark",
      "DJ ChrisToSs",
      "DJ Alinco",
      "DJ Vodka",
      "DJ Lawy",
      "DJ OP Dot",
      "DJ OBA45",
      "DJ Symple",
      "Deejay Biggy",
      "DJ Anunnaki",
      "DJ Tolly P",
      "DJ Danny Yung",
      "DJ Lovely",
      "DJ Rider",
      "DJ Wizkel",
      "DJ Black",
      "CYRIL",
      "DJ Fletzy",
      "DJ Shabsy",
      "DJ Prince",
      "DJ Buckz",
      "DJ Pelzy",
      "DJ Chi",
      "Black Coffee",
      "DJ Maphorisa",
      "Kabza De Small",
      "DJ Kent",
      "DJ Fresh",
      "Prince Kaybee",
      "Shimza",
      "Oscar Mbo",
      "DJ Vyrusky",
      "DJ Mensah",
      "DJ Switch",
      "DJ Mic Smith",
      "DJ Krush",
      "DJ Kaori",
      "DJ Kentaro",
      "Carta",
      "Chace",
      "DJ Wordy",
      "Raiden",
      "HYO",
      "DJ Soda",
      "Peggy Gou",
      "Nucleya",
      "DJ Chetas",
      "DJ Aqeel",
      "Zaeden",
    ],
  },
];

export function getCountry(id: string) {
  return curatedCountries.find((c) => c.id === id);
}

export function allCuratedArtistNames() {
  const set = new Set<string>();
  curatedCountries.forEach((c) => c.artists.forEach((a) => set.add(a)));
  return Array.from(set);
}
