import { curatedCountries } from "./curated-artists";
import { searchCuratedSongs, type CuratedSongHit } from "./curated-library";

export type { CuratedSongHit };
export { searchCuratedSongs };

/** Common alternate spellings → canonical curated name */
const ALIASES: Record<string, string> = {
  kiss: "Kizz Daniel",
  kizz: "Kizz Daniel",
  "kiss daniel": "Kizz Daniel",
  "kizz daniel": "Kizz Daniel",
  "kiss daniels": "Kizz Daniel",
  "2face": "2Baba",
  "2 face": "2Baba",
  "2baba": "2Baba",
  mi: "MI Abaga",
  "m.i": "MI Abaga",
  "m.i abaga": "MI Abaga",
  fireboy: "Fireboy DML",
  bnxn: "BNXN",
  buju: "BNXN",
  "ti blaze": "T.I BLAZE",
  "t.i blaze": "T.I BLAZE",
  "wiz kid": "Wizkid",
  wizkid: "Wizkid",
  davido: "Davido",
  olamide: "Olamide",
  baddo: "Olamide",
  oritse: "Oritse Femi",
  femi: "Oritse Femi",
  "oritse femi": "Oritse Femi",
  oritsefemi: "Oritse Femi",
  temilade: "Tems",
  tems: "Tems",
  ayra: "Ayra Starr",
  "ayra star": "Ayra Starr",
  "young john": "Young Jonn",
  "young jonn": "Young Jonn",
  mohbad: "Mohbad",
  "seyi vibez": "Seyi Vibez",
  "adekunle gold": "Adekunle Gold",
  agba: "Adekunle Gold",
  asake: "Asake",
  "tope alabi": "Tope Alabi",
  "sunmisola": "Sunmisola Agbebi",
  sunmisola: "Sunmisola Agbebi",
  bidemi: "Bidemi Olaoba",
  "bidemi olaoba": "Bidemi Olaoba",
  ijoya: "Oritse Femi",
  anchovy: "Kizz Daniel",
  kuleko: "Kizz Daniel",
  sability: "Ayra Starr",
  aquafina: "Young Jonn",
  asap: "Shallipopi",
  "shallipopi": "Shallipopi",
  aletile: "Oritse Femi",
  "afro jigga": "Ladipoe",
  ladipoe: "Ladipoe",
  "ladi poe": "Ladipoe",
  anabella: "Khaid",
  asiwaju: "Ruger",
  aye: "Davido",
  "taye turaya": "Taye Currency",
  basket: "Taye Currency",
  "di ja": "Di'ja",
  dija: "Di'ja",
  bandana: "Fireboy DML",
  "benin boys": "Rema",
  "tshwala bam": "TitoM",
  "tshwala": "TitoM",
  italawa: "G.O.E",
  "bad vibes": "Ayra Starr",
  "bad girl riri": "Yonda",
  shako: "Barry Jhay",
  "365 days": "Bella Shmurda",
  "calm down": "Rema",
  buga: "Kizz Daniel",
  "cough": "Kizz Daniel",
  odo: "Kizz Daniel",
  machala: "Carterefe",
  tikuku: "Candy Bleakz",
  "chop my money": "P-Square",
  "come closer": "Wizkid",
  commas: "Ayra Starr",
  "call of duty": "Zinoleesky",
  kilometer: "BNXN",
  dupe: "Asake",
  egwu: "Chike",
  "don't matter": "Akon",
  "dont matter": "Akon",
  "deja vu": "Seyi Vibez",
  dejavu: "Seyi Vibez",
  "emi lo kan": "Qdot",
  "ello baby": "Young Jonn",
  peru: "Fireboy DML",
  finesse: "Pheelz",
  "feran mi": "Kizz Daniel",
  gwagwalada: "BNXN",
  godly: "Omah Lay",
  gobe: "Davido",
  "for my hand": "Burna Boy",
  "i love lagos": "Olamide",
  ibibe: "DJ Xclusive",
  ibele: "Lil Kesh",
  ibile: "Lil Kesh",
  ifunanya: "J. Martins",
  "in my maserati": "Olakira",
  hustle: "Teni",
  jinja: "Olamide",
  jara: "Khaid",
  jolie: "Khaid",
  katapot: "Reekado Banks",
  jaboti: "Zlatan",
  kelele: "Oritse Femi",
  laye: "Kizz Daniel",
  loading: "Olamide",
  limpopo: "Kcee",
  "ma pariwo": "Zinoleesky",
  "marlian": "Mohbad",
  sope: "Mohbad",
  "nwa baby": "Flavour",
  "new religion": "Olamide",
  normally: "Young Jonn",
  "mungo park": "Korede Bello",
  korede: "Korede Bello",
  "mr money": "Asake",
  "ole lazy": "Muraino",
  "never took the time": "Akon",
  "omo to shan": "Oritse Femi",
  "oluwa ni": "Reekado Banks",
  "olowo nla": "Odunayo Akintomide",
  "olorun agbaye": "Nathaniel Bassey",
  olorun: "Asake",
  "one question": "Wizkid",
  "one side": "Iyanya",
  "on top your matter": "Wizkid",
  omolope: "Oritse Femi",
  "orin emi": "Qdot",
  "ori owo": "Tillaman",
  organise: "Asake",
  opo: "2Baba",
  "oro aje": "Oritse Femi",
  poko: "Kizz Daniel",
  "poco dance": "Poco Lee",
  ybnl: "Olamide",
  rtid: "Kizz Daniel",
  "rich till i die": "Kizz Daniel",
  gbeja: "Qdot",
  "psalm 23": "Seyi Vibez",
  "thy kingdom come": "Seyi Vibez",
  "preke na preke": "Super D",
  rora: "Lil Kesh",
  ronaldo: "Mohbad",
  romantic: "Korede Bello",
  "second sermon": "Black Sherif",
  "scape goat": "D'banj",
  sabi: "Mohbad",
  "over sabi": "Seyi Vibez",
  "hat-trick": "Seyi Vibez",
  "hat trick": "Seyi Vibez",
  "sexy lady": "Oritse Femi",
  "see you again": "Wiz Khalifa",
  "raatan lambiyan": "Jubin Nautiyal",
  "no more condition": "Rexxie",
  sanumi: "Oritse Femi",
  fola: "Fola",
  "opra mini": "Poco Lee",
  "fuji garbage": "Olamide",
  "nack am": "Candy Bleakz",
  kukere: "Iyanya",
  "fake fam": "Oritse Femi",
  uju: "B Red",
  "sha guide": "Portable",
  "walking dead": "Mohbad",
  "olo noni": "Oritse Femi",
  "omo logo": "Hysaint",
  "da yan mo": "DJ Jimmy Jatt",
  jogodo: "Wizkid",
  goated: "Tml Vibez",
  "body tuff": "Tml Vibez",
  "hey stranger": "Reekado Banks",
  "eko miami": "Maleek Berry",
  "shkran lak": "Bhadboi OML",
  "7am in lekki": "Bhadboi OML",
  "easy jeje": "Reekado Banks",
  kude: "Harry Cane",
  meow: "Scope",
  sooner: "Young Jonn",
  sharpally: "Young Jonn",
  "full my tank": "Young Jonn",
  "maya maya": "Young Jonn",
  "bhadboi": "Bhadboi OML",
  "bhad boy oml": "Bhadboi OML",
  bahamas: "Young Jonn",
  "pot of gold": "Young Jonn",
  "tony montana": "Young Jonn",
  "2factor": "Young Jonn",
  "fuji fusion": "Bella Shmurda",
  "fuji moto": "Seyi Vibez",
  oleku: "Ice Prince",
  aboki: "Ice Prince",
  gbese: "Majeeed",
  kasongo: "Harry Cane",
  kamake: "Oritse Femi",
  "osunmo grammy": "Portable",
  copines: "Aya Nakamura",
  arike: "Kunmie",
  okpeke: "Phyno",
  duro: "Tekno",
  "tit for tat": "Tate McRae",
  "hood scars": "J.I the Prince of N.Y",
  "to be a man": "Kizz Daniel",
  tesumole: "Naira Marley",
  kojosese: "Naira Marley",
  "opotoyi": "Naira Marley",
  dakun: "Olawale Imole",
  "bum bum": "Timaya",
  bubalu: "Rema",
  "too faithful": "Moses Bliss",
  omoge: "Slim Joe",
  biko: "Lola Rae",
  porsche: "T.I BLAZE",
  "sandra benede": "Portable",
  jailer: "Olamide",
  "dodoyo": "Portable",
  folded: "Kehlani",
  "i alone": "BNXN",
  "very soon": "BNXN",
  "billionaires club": "Olamide",
  ijebu: "Modupe",
  orijin: "Qdot",
  "ijo gelede": "Qdot",
  "group chat": "Portable",
  gaddem: "Rybeena",
  "al-jannah": "Kizz Daniel",
  "al jannah": "Kizz Daniel",
  molue: "Kizz Daniel",
  "are you alright": "Kizz Daniel",
  "boys are bad": "Kizz Daniel",
  "day by day": "Simi",
  titi: "Kizz Daniel",
  "black girl magic": "Kizz Daniel",
  bebo: "Burna Boy",
  adimula: "Portable",
  "yahyuppiyah": "Uncle Waffles",
  agbalumo: "Seriki",
  "ka valungu": "Tebza De DJ",
  mnike: "Tyler ICU",
  smsg: "Barry Jhay",
  "see me see god": "Barry Jhay",
  "the chairman": "MI Abaga",
  "street runner": "Rod Wave",
  "find money": "Ayo Maff",
  "loke loke": "Sean Tizzle",
  oriade: "Portable",
  "saka nana": "Uhuru",
  "beautiful girls": "Sean Kingston",
  "another level": "Patoranking",
  "happy song": "Seyi Vibez",
  "kiss me": "Kizz Daniel",
  jombo: "Kizz Daniel",
  napo: "Kizz Daniel",
  "nothing dey": "Kizz Daniel",
  "love no go die": "Olamide",
  implication: "2Baba",
  "melo melo": "Olamide",
  "chop my money": "P-Square",
  "i concur": "Timaya",
  sekem: "MC Galaxy",
  "warn dem": "DJ Kaywise",
  adun: "Sunmisola Agbebi",
  "daddy yo": "Wizkid",
  "oliver twist": "D'banj",
  "yori yori": "Bracket",
  kerewa: "Zule Zoo",
  peaches: "Justin Bieber",
  jaiye: "Oritse Femi",
  "ile aiye": "Oritse Femi",
  "on rewind": "Oritse Femi",
  kabiyesi: "Dr SID",
  "peace i chose": "Kizz Daniel",
  "love me like you do": "Ellie Goulding",
  "iya alariya": "9ice",
  "dali wami": "King Temoso",
  "tshwala bam": "TitoM",
  upgrade: "Bella Shmurda",
  pipa: "Kizz Daniel",
  oyibe: "Kizz Daniel",
  "time no dey": "Kizz Daniel",
  "se bi wo": "Lace",
  sebiwo: "Lace",
  "eni duro": "Olamide",
  jaho: "Kizz Daniel",
  raba: "DJ Shabsy",
  "e better": "Kizz Daniel",
  ebetter: "Kizz Daniel",
  chana: "Kizz Daniel",
  "only me": "Asake",
  "soweto baby": "DJ Maphorisa",
  "nowo soke": "CDQ",
  "10 over 10": "Naeto C",
  "my woman my everything": "Patoranking",
  "pxy drip": "Naira Marley",
  ireti: "Oritse Femi",
  "joy is coming": "Fido",
  "aya oba": "Shadykarz",
  omodele: "Shadykarz",
  "double wahala": "Oritse Femi",
  "god pikin": "Oritse Femi",
  "ara n bada": "Oritse Femi",
  "mr gomina": "Shadykarz",
  "i testify": "Ada Ehi",
  ameno: "Nektunez",
  "gbe body": "Adegbodu Twins",
  timbolo: "Danny S",
  "upon me": "Kizz Daniel",
  idan: "Oritse Femi",
  "sexy rosey": "Flavour",
  kokoma: "K9",
  "jaiye jaiye": "Wizkid",
  "mummy mi": "Wizkid",
  "omo ologo": "Pasuma",
  "toma toma": "Ruger",
  logba: "Tml Vibez",
  "pano tona": "Kizz Daniel",
  "you go wait": "Demmie Vee",
  dilika: "KayGee DaKing",
  "a thousand years": "Christina Perri",
  "slow down": "R2Bees",
  "baddest boy": "EME All Stars",
  "olohun ojee": "Pasuma",
  aii: "Kizz Daniel",
  yapa: "Kizz Daniel",
  mukulu: "Skales",
  ase: "Bella Shmurda",
  "omo alhaji": "Ycee",
  durosoke: "Olamide",
  personally: "P-Square",
  alingo: "P-Square",
  "wedding day": "Kizz Daniel",
  casanova: "Shadykarz",
  "yeye boyfriend": "Zlatan",
  shayo: "Bigiano",
  "perfect gentleman": "Sean Tizzle",
  "fi kan we kan": "BNXN",
  aileyipada: "Sunmisola Agbebi",
  "are you there": "Ayo Maff",
  "rhythm and blues": "Ayra Starr",
  "rhythm & blues": "Ayra Starr",
  "never be the same": "Camila Cabello",
  "thank god for me": "Kizz Daniel",
  "side chick": "Kizz Daniel",
  bolanle: "IVD",
  "sanwo mi": "King Soundboi",
  komasava: "Diamond Platnumz",
  runmo: "Oritse Femi",
  opor: "Lil Kesh",
  "jump am pass": "Terry G",
  "vula sekele": "Harry Cane",
  malwedhe: "King Monada",
  chiwana: "King Monada",
  marhaba: "Kizz Daniel",
  "romeo must die": "Ruger",
  rmd: "Ruger",
  "way back": "Khaid",
  "my dealer": "Kaestyle",
  alabarin: "Tope Alabi",
  "story for the gods": "Olamide",
  ibadi: "DJ Kamol",
  "holla at your boy": "Wizkid",
  "don't dull": "Wizkid",
  "oluwa lo ni": "Wizkid",
  azaman: "Rema",
  "run mad": "Terry G",
  poe: "Ruger",
  "men are crazy": "Simi",
  "ogo cele": "Portable",
  pakurumo: "Wizkid",
  "no lele": "Wizkid",
  "gidi girl": "Wizkid",
  "sexy mama": "Iyanya",
  mapariwo: "Zinoleesky",
  "xtra cool": "Young Jonn",
  yahooze: "Olu Maintain",
  yanga: "Chidinma",
  "yemi my lover": "Olamide",
  yawa: "Fireboy DML",
  waloda: "Lil Frosh",
  "you bad": "Wande Coal",
  "you know": "Small Doctor",
  "you dey whine me": "Austine Emmanuel",
  "wait for me": "Johnny Drille",
  "won da mo": "Mavins",
  woju: "Kizz Daniel",
  "who you epp": "Olamide",
  "wells fargo": "Vibez Inc",
  "way maker": "Sinach",
  "too busy to be bae": "Kizz Daniel",
  "twe twe": "Kizz Daniel",
  "sweet as e be": "Remy Crown",
  "summer body": "Olamide",
  "sugar mama": "Joeboy",
  "jaiye foreign": "Tiwa Savage",
  "the real mvp": "Olamide",
  "won yabo": "Rexxie",
  "injure me": "Teni",
  tambolo: "Portable",
  "standing ovation": "Tiwa Savage",
  "who is your guy": "Spyro",
  skelemba: "Olamide",
  "sisi nene": "Wizkid",
  "shu-peru": "Kizz Daniel",
  "shu peru": "Kizz Daniel",
  showa: "Kizz Daniel",
  shoki: "Lil Kesh",
  sofa: "Kizz Daniel",
  "so cold": "Bella Shmurda",
  snapchat: "Ruger",
  sokoto: "Minz",
};

/** Short keys must match exactly so "mi" / "kiss" don't over-match */
const EXACT_ONLY_ALIASES = new Set([
  "mi",
  "kiss",
  "kizz",
  "femi",
  "buju",
  "ayra",
  "tems",
  "aye",
  "asap",
  "basket",
  "cough",
  "odo",
  "titi",
  "idan",
  "aii",
  "ase",
  "poe",
  "rmd",
  "woju",
]);

function normalize(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9\s.]/g, " ").replace(/\s+/g, " ").trim();
}

function resolveAliasTarget(q: string): string | null {
  if (!q) return null;
  if (ALIASES[q]) return ALIASES[q];

  let best: { key: string; target: string; score: number } | null = null;
  for (const [key, target] of Object.entries(ALIASES)) {
    if (EXACT_ONLY_ALIASES.has(key)) continue;
    let score = 0;
    if (key.startsWith(q) || q.startsWith(key)) score = 90;
    else if (key.includes(q) && q.length >= 4) score = 70;
    if (score > 0 && (!best || score > best.score || key.length < best.key.length)) {
      best = { key, target, score };
    }
  }
  return best?.target ?? null;
}

export interface CuratedArtistHit {
  name: string;
  countryId: string;
  countryName: string;
  flag: string;
  score: number;
}

export function searchCuratedArtists(query: string, limit = 24): CuratedArtistHit[] {
  const q = normalize(query);
  if (!q || q.length < 2) return [];

  const aliasTarget = resolveAliasTarget(q);
  const hits = new Map<string, CuratedArtistHit>();

  for (const country of curatedCountries) {
    for (const name of country.artists) {
      const n = normalize(name);
      let score = 0;
      if (aliasTarget && normalize(aliasTarget) === n) score = 120;
      else if (n === q) score = 100;
      else if (n.startsWith(q) || q.startsWith(n)) score = 80;
      else if (n.includes(q)) score = 60;
      else {
        const tokens = q.split(" ").filter(Boolean);
        if (tokens.length > 1 && tokens.every((t) => n.includes(t))) score = 50;
        else if (tokens.some((t) => t.length > 2 && n.includes(t))) score = 25;
      }

      if (score <= 0) continue;
      const existing = hits.get(name);
      if (!existing || score > existing.score) {
        hits.set(name, {
          name,
          countryId: country.id,
          countryName: country.name,
          flag: country.flag,
          score,
        });
      }
    }
  }

  return Array.from(hits.values())
    .sort((a, b) => b.score - a.score || a.name.localeCompare(b.name))
    .slice(0, limit);
}

export function resolveCuratedArtistName(query: string): string | null {
  const hits = searchCuratedArtists(query, 1);
  return hits[0]?.score >= 50 ? hits[0].name : null;
}
