// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elyjmqmluldzlptxmabi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_yTYbyKH08xYRIqzkkk1npA_rgfE8Sv_";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function authStorage(): Storage {
  try {
    const probe = "__ds_probe";
    window.localStorage.setItem(probe, "1");
    window.localStorage.removeItem(probe);
    return window.localStorage;
  } catch {
    const map = new Map<string, string>();
    return {
      get length() {
        return map.size;
      },
      clear() {
        map.clear();
      },
      getItem(key) {
        return map.get(key) ?? null;
      },
      key(index) {
        return [...map.keys()][index] ?? null;
      },
      removeItem(key) {
        map.delete(key);
      },
      setItem(key, value) {
        map.set(key, value);
      },
    };
  }
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});